@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

class GSM {
name
email
password
}

class Entry {
stateOfEntry
greenSpace
titleOfEntry
descriptionOfEntry
approximateExpectedDuration
degreeOfUrgency
}


GSM "1" -- "0..*" Entry : Add >
@enduml