@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0

left to right direction

package "UI" #f0f0f0{
    class ViewDetailsEntryUI {
        +showEntryDetails(entryDto: EntryDto): void
    }

    class AgendaUI {
    }

    AgendaUI ..> ViewDetailsEntryUI
}
package "Core" #f0f0f0{

    package "Controller" #dddddd{

        class ViewDetailsEntryController {
            +getDataNeeded()
        }

        ViewDetailsEntryUI ..>  ViewDetailsEntryController


        class AgendaController {
            +getAgendaEntryListDto(): List<EntryDto>
        }

        AgendaUI ..> AgendaController
    }

    package "Domain" #dddddd{


        package "Mapper" #dddddd{

            class EntryMapper {
                +toDTO(entryList: List<Entry>): List<EntryDto>
            }

            AgendaController ..> EntryMapper

            class TeamMapper {
                +toDTO(teamList: List<Team>): List<TeamDto>
            }
            ViewDetailsEntryController ..> TeamMapper

            class VehicleMapper {
                +toDTO(vehicleList: List<Vehicle>): List<VehicleDto>
            }
            ViewDetailsEntryController ..> VehicleMapper

        }

        package "DTO" #dddddd{

            class EntryDto {
                +startDate: Date
                +status: String
                +teamAssigned: TeamDto
                +reference: String
            }
            
            EntryMapper ..> EntryDto

            class TeamDto {
                +teamName: String
            }
            
            TeamMapper ..> TeamDto

            class VehicleDto {
                brand: String
                model: String
                plate: String
            }

            VehicleMapper ..> VehicleDto


        }

        package "Repository" #bbbbbb{

            class Repositories {
                - static instance : Repositories
                + getInstance() : Repositories
                + getEntryRepository() : EntryRepository
                + getTeamRepository() : TeamRepository
                +getVehicleRepository(): VehicleRepository
                - Repositories()
            }

            ViewDetailsEntryController ..> Repositories : repositories
            AgendaController ..> Repositories : repositories

            Repositories --> Repositories : instance

            class EntryRepository {
                +assignTeamToEntry(team: Team, entryDto: EntryDto): boolean
                +findEntryByReference(reference: String): Entry
                +getAgenda(): List<Entry>
            }

            Repositories "1" --> "1" EntryRepository : entryRepository
            AgendaController ..> EntryRepository : entryRepository

            class TeamRepository {
                +getTeamList(): List<Team>
            }

            Repositories "1" --> "1" TeamRepository : teamRepository
            ViewDetailsEntryController ..> TeamRepository: teamRepository

            class VehicleRepository {
                +getVehicleList(): List<Vehicle>
            }

            Repositories "1" --> "1" VehicleRepository : VehicleRepository
            ViewDetailsEntryController ..> VehicleRepository: VehicleRepository

        }

        package "Model" #bbbbbb{

            class Entry {
                +reference: String
                +status: String
                +startDate: Date
                +teamAssigned: Team
                +finishDate: Date
            }

            EntryRepository "1" --> "*" Entry
            EntryMapper  ..> Entry

            class Team {
                +name: String
                +maxSize: int
                +minSize: int
            }

            TeamRepository "1" --> "*" Team
            TeamMapper  ..> Team

            class Vehicle {
                brand: String
                model: String
                plate: String
            }

            VehicleRepository "1" --> "*" Vehicle
            VehicleMapper  ..> Vehicle
        }



    }
}

@enduml
