
@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":VehicleMapper" as VehicleMapper

participant "vehicleList:list<Vehicle>" as VehicleList
participant "vehicleListDto:list<VehicleDto>" as VehicleListDto
participant "objDto:VehicleDto" as VehicleDto 

-> VehicleMapper : toDTO(teamList)
autonumber 8.13.1
activate VehicleMapper
group Convert Team List to DTO
    
   VehicleMapper -> VehicleListDto** : create()

        loop for each object in VehicleList
            VehicleMapper -> VehicleList : obj = get()
            activate VehicleList
            deactivate VehicleList
            VehicleMapper -> VehicleMapper: objDto = toDto(obj)
            activate VehicleMapper

            VehicleMapper -> VehicleDto** : create(obj.getBrand(), obj.getModel(), obj.getPlate())
            deactivate VehicleMapper
            VehicleMapper -> VehicleListDto : add(objDto)
            activate VehicleListDto
            deactivate VehicleListDto
        end

        deactivate VehicleList

    end

    autonumber 8.14
    <- VehicleMapper  : vehicleListDto
    deactivate VehicleMapper

    @enduml
