@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "HRM" as HRM
participant ":GenerateTeamUI" as UI
participant ":GenerateTeamController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillRepository\n:SkillRepository" as SkillRepository
participant "organization\n:Organization" as ORG
participant "team\n:Team" as Team

activate HRM

        HRM -> UI : asks to generate a Team automatically

        activate UI

'           UI --> HRM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create


            UI --> HRM : requests data
        deactivate UI

        HRM -> UI : types requested data(maxSizeTeam, minSizeTeam)
        activate UI




    UI -> CTRL : getSkillList()
                activate CTRL

                    CTRL -> RepositorySingleton : getInstance()
                    activate RepositorySingleton

                        RepositorySingleton --> CTRL: repositories
                    deactivate RepositorySingleton

                    CTRL -> PLAT : getSkillRepository()
                    activate PLAT

                        PLAT --> CTRL: skillRepository
                    deactivate PLAT

                    CTRL -> SkillRepository : getSkillList()
                    activate SkillRepository

                        SkillRepository --> CTRL : skillList
                    deactivate SkillRepository

    CTRL --> UI : skillList
    deactivate CTRL



    UI --> HRM : shows skillList\n and asks to introduce the skill(s)
    deactivate UI
    loop While adding skill
    HRM -> UI : select the skill
    activate UI

        UI --> HRM : shows skillSet and ask if \n want to introduce more or request data
    deactivate UI
    end
    HRM -> UI : submits data
    activate UI

        UI -> CTRL : generateTeam(maxSizeTeam,minSizeTeam,skillSet)
        activate CTRL



            CTRL -> ORG:generateTeam(maxSizeTeam,minSizeTeam,skillSet)
            activate ORG

                ORG -> Team**: create()

                loop Until you have the full team
                ORG -> ORG: validateCollaborator(collaboratorNotActivateList, skillSet)
                activate ORG

                    ORG -> Team: addCollaborator(collaborator)
                    activate Team

                        Team --> ORG
                    deactivate Team

                    ORG --> ORG
                deactivate ORG
                end

                ORG --> CTRL : team / collaboratorNotActivateList

            deactivate ORG

            CTRL --> UI: team / collaboratorNotActivateList
            deactivate CTRL
            UI --> HRM : show team and confirm or modify data
    deactivate UI

    loop
    HRM -> UI : modify data
    activate UI

    UI --> HRM : remove or add
    deactivate UI
    HRM -> UI : addCollaborator
    activate UI

    UI -> CTRL : getCollaboratorNotActivateList
    activate CTRL

    CTRL --> UI : collaboratorNotActivateList
    deactivate CTRL

    UI --> HRM : show collaboratorNotActivateList and ask Collaborator to add
    deactivate UI

    HRM -> UI : indexCollaborator
    activate UI

    UI -> CTRL : addCollaboratorTeam(indexCollaborator,team)
    activate CTRL

    CTRL -> ORG : validateCollaboratorByIndex(indexCollaborator, collaboratorNotActivateList, team)
    activate ORG

        ORG -> Team: addCollaborator(collaborator)
                        activate Team

                            Team --> ORG
                        deactivate Team

    ORG --> CTRL : team / collaboratorNotActivateList


    deactivate ORG



    CTRL -> UI : team / collaboratorNotActivateList
    deactivate CTRL
                UI --> HRM : show team and confirm or modify data
        deactivate UI


    end


    HRM -> UI: confirms data
    activate UI


    UI -> CTRL : saveTeam(team)
    activate CTRL

    CTRL -> ORG : saveTeam(team)
    activate ORG
    activate ORG
    ORG -> ORG : saveTeam(team)
    deactivate ORG

    ORG --> CTRL : true
    deactivate ORG

    CTRL --> UI : true
    deactivate CTRL

    UI --> HRM : success operation
    deactivate UI


deactivate HRM

@enduml