@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ApplicationSession{
    + static getInstance()
    + getCurrentSession()
}

class UserSession{
}

class HRM {
}

class Collaborator {
    - name
    - date of birthday
    - admission data
    - address street zipcode
    - address city, email
    - phone number
    - docType
    - docIDNumber
    - jobCategory

    + Collaborator(name, date of birthday, admission data, address street,\n zipcode, address city, email, phone number, docType,\n docIDNumber, jobCategory)
}

class Skill {
    - String name
    + Skill(name)
}

class CollaboratorRepository {
    - List <Collaborator> collaboratorsNotActivate
    - List <Collaborator> collaboratorsActivate
    + getCollaboratorList()
    + activateCollaborator(team)
}

class TeamRepository {
    - List <Team>
    + generateTeamBySkillSetAndSize(minSizeTeam,maxSizeTeam,skillsSelected,collaboratorsNotActivate)
    + getTeamList()
}

class SkillRepository{
    - List <Skill>
    + getSkillList()
}

class Team{
    -Integer maxSizeTeam
    -Integer minSizeTeam
    -List <Skill> requiredSkills
    -List <Collaborator> collaboratorsTeam
    + Team(maxSizeTeam,minSizeTeam,collaboratorsList,skillsSelected)
    + getTeamList()
    + Optional <Team> addCollaborator
}


class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getJobCategoryRepository()
    + getCollaboratorRepository()
    + getTeamRepository()
}

class GenerateTeamController {
    + RegisterCollaboratorController(collaboratorRepository, jobCategoryRepository)
    + getSkillList()
    + getCollaboratorsNotActivate()
    + generateTeam(minSizeTeam,maxSizeTeam,skillsSelected,collaboratorsNotActivate)
    + activateCollaboratorsList(team)
    - getHRMFromSession()
}

class SkillRepository{
    - List <Skill>
    + getSkillList()
}

note right of GenerateTeamController
    - userEmail is obtained
    from the user session
    - skillList
    is achieved with skill repository
end note

note bottom of SkillRepository
    - used for displaying
    the job category list
end note

class GenerateTeamUI {
}

Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance

GenerateTeamUI .> GenerateTeamController

GenerateTeamController .> Repositories : repositories

Repositories --> "1" CollaboratorRepository
Repositories --> "1" SkillRepository
Repositories --> "1" TeamRepository

GenerateTeamController ..> CollaboratorRepository : CollaboratorRepository
GenerateTeamController ..> SkillRepository : SkillRepository
GenerateTeamController ..> TeamRepository : TeamRepository


GenerateTeamController ..> "1" CollaboratorRepository : collaboratorRepository
GenerateTeamController ..> ApplicationSession
GenerateTeamController ..> UserSession

CollaboratorRepository "1" --> "*" Collaborator : collaborators
TeamRepository "1" --> "*" Team : teams
SkillRepository "1" --> "*" Skill : skills

Team --> HRM : generatedBy

ApplicationSession --> "1" UserSession : userSession

TeamRepository --> "*" HRM : employs
SkillRepository --> "*" HRM : employs
CollaboratorRepository --> "*" HRM : employs


@enduml