@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":JobController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "docTypeRepository:\ndocTypeRepository" as DocTypeRepository

autonumber 12
-> CTRL : getJobCategoryByDescription(jobCategoryDescription)

autonumber 12.1

activate CTRL
    group Verify DocIDNumber
                                    CTRL -> RepositorySingleton : getInstance()
                                    activate RepositorySingleton

                                        RepositorySingleton --> CTRL: repositories
                                    deactivate RepositorySingleton

                                    CTRL -> PLAT : getDocTypeCategoryRepository()
                                    activate PLAT

                                        PLAT --> CTRL: docTypeCategoryRepository
                                    deactivate PLAT

                                    CTRL -> DocTypeRepository : verifyDocType(docIDNumber)
                                    activate DocTypeRepository

                                        DocTypeRepository --> CTRL : true/false
                                    deactivate DocTypeRepository
    end group

    autonumber 13
    <-- CTRL : true

deactivate CTRL


@enduml