@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class Entry {
    reference String
    status
    startDate
    finishDate
}

class Collaborator {
    name
    email
}


Collaborator "1" -- "*" Entry : completes >

@enduml
