@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "GSM" as Manager
participant ":System" as System

activate Manager 

    Manager -> System : asks to add a new entry to the To-Do List
    activate System

    System --> Manager : show degree of urgency list and ask to select one
    deactivate System

    Manager -> System : selects the urgency degree
    activate System

    System --> Manager : requests data (expected duration)
    deactivate System

   Manager  -> System : types data
    activate System

   System --> Manager : show data and request confirmation
    deactivate System

   Manager  -> System : confirm data
    activate System

   System --> Manager : display operation success
    deactivate System

@enduml