@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "GSM" as Manager
participant ":System" as System

activate Manager

    Manager -> System : asks to register a new green space
    activate System


    System --> Manager  : Displays all available green space types and requests\n the name, address, area, and type for the new green space
        deactivate System

        Manager  -> System :Provides the name, address, area, and selects a green space type
        activate System


       System  --> Manager : displays operation success


@enduml
