@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

class Collaborator {
    job
    task
    name
    birthdate
    admissionDate
    address
    mobileNumber
    email
    docType
    docNumber
}

class Skill {
    name
}

Collaborator "0..*" -r- "0..*" Skill : possesses 

@enduml
