@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUserEmail()
}

class Employee {
    - name
    - email
    - position
    - phone
}

class Vehicle {
    - String brand
    - String model
    - Integer plate
    - String type
    - Integer tare
    - String grossWeight
    - Integer currenteKM
    - String registerDate
    - String acquisitionDate
    - Integer checkupFrequency

    + Vehicle(brand, model, plate, type, tare, grossWeight, currenteKM, registerDate, acquisitionDate, checkupFrequency)
}



class VehicleCheckUpRepository {
    + getVehicleByBrand(brand)
    + getVehicleCehckUpList()

}


class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getVehicleRepository()
}

class VehicleCheckUpController {
    + VehicleCheckUpController(vehicleRepository)
    - getEmployeeFromSession()
}

note right of VehicleCheckUpController
    - userEmail is obtained
    from the user session
    - categoryDescription
    is retrieved from selected data

end note

note bottom of VehicleCheckUpRepository
    - used for displaying
    the vehicle list
end note

class VehicleCheckUpUI {
}


Repositories -> "1" VehicleCheckUpRepository
Repositories -> Repositories : instance

ApplicationSession -> ApplicationSession : instance
ApplicationSession --> "1" UserSession : userSession

VehicleCheckUpUI .> VehicleCheckUpController

VehicleCheckUpController .> Repositories : repositories
VehicleCheckUpController ..> ApplicationSession
VehicleCheckUpController ..> UserSession
VehicleCheckUpController ..> VehicleCheckUpRepository : VehicleCheckUpRepository
VehicleCheckUpController ..> VehicleCheckUpRepository : VehicleCheckUpRepository

Vehicle --> Employee : createdBy

VehicleCheckUpRepository "1" --> "*" Vehicle : vehicles

@enduml