@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "VFM" as VFM
participant ":VehicleCheckUpUI" as UI

participant ":VehicleCheckUpController" as CTRL

participant ":Repositories" as Repositories
participant "Repositories" as Repos
participant "vehicleCheckUpRepository\n:VehicleCheckUpRepository" as VehicleCheckUpRepository

activate VFM

    VFM -> UI : asks the list of vehicles for check-up
    activate UI

    UI -> CTRL : getVehicleCheckUpList()
    activate CTRL

    CTRL -> Repositories : getInstance()
    activate Repositories

    Repositories --> CTRL : repositories
    deactivate Repositories

    CTRL -> Repos : getVehicleCheckUpRepository()
    activate Repos

    Repos --> CTRL :vehicleCheckUpRepository
    deactivate Repos

    CTRL -> VehicleCheckUpRepository : getVehicleCheckUpList()
    activate VehicleCheckUpRepository

    VehicleCheckUpRepository --> CTRL : vehicleCheckUpList
    deactivate VehicleCheckUpRepository

    deactivate VehicleCheckUpRepository

    CTRL --> UI: true / vehicleCheckUpList
    deactivate CTRL

    UI --> VFM : shows the list of vehicles

    VFM -> UI : ask to confirm data

    UI --> VFM : displays operation success
    deactivate UI

deactivate VFM

@enduml