@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "VFM" as VFM
participant ":VehicleUI" as UI
participant ":VehicleCheckUpController" as CTRL
participant ":Repositories" as Repositories
participant "vehicleCheckUpRepository\n:VehicleCheckUpRepository" as VehicleCheckUpRepository
participant "vehicle\n:Vehicle" as Vehicle

activate VFM

    VFM -> UI : asks the list of vehicles for check-up
    activate UI

    UI -> CTRL : getVehicleCheckUpList()
    activate CTRL

    CTRL -> Repositories : getInstance()
    activate Repositories

    Repositories -> CTRL : repositories
    deactivate Repositories

    CTRL -> VehicleCheckUpRepository : getVehicleCheckUpRepository()
    activate VehicleCheckUpRepository

    VehicleCheckUpRepository -> CTRL :vehicleCheckUpRepository
    deactivate VehicleCheckUpRepository

    CTRL -> Repositories : getVehicleCheckUpList()

    Repositories -> VehicleCheckUpRepository : getVehicleCheckUpList()

    VehicleCheckUpRepository -> Repositories : vehicleCheckUpList

    CTRL -> Repositories : getVehicleRepository()

    Repositories -> VehicleCheckUpRepository : getVehicleRepository()

    VehicleCheckUpRepository --> Repositories : vehicleCheckUpRepository
    deactivate VehicleCheckUpRepository

    Repositories --> CTRL: repositories

    VehicleCheckUpRepository -> Vehicle: createVehicle()

    Vehicle -> VehicleCheckUpRepository: addVehicle(vehicle)

    VehicleCheckUpRepository --> Repositories : true / vehicle

    Repositories --> CTRL : true / vehicle
    deactivate Repositories

    deactivate VehicleCheckUpRepository

    CTRL --> UI: true / vehicle
    deactivate CTRL

    UI -> VFM : shows the list of vehicles

    VFM -> UI : confirms data

    UI -> VFM : displays operation success
    deactivate UI

deactivate VFM

@enduml