@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUserEmail()
}

class Employee {
    - name
    - email
    - position
    - phone
}

class Vehicle {
    - String brand
    - String model
    - Integer plate
    - String type
    - Integer tare
    - String grossWeight
    - Integer currenteKM
    - String registerDate
    - String acquisitionDate
    - Integer checkupFrequency

    + Vehicle(brand, model, plate, type, tare, grossWeight, currenteKM, registerDate, acquisitionDate, checkupFrequency)
}



class VehicleRepository {
    + getVehicleByBrand(brand)
    + getVehicleCehckUpList()

}


class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getVehicleRepository()
}

class CheckUpListController {
    + CheckUpListController(vehicleRepository)
    - getEmployeeFromSession()
}

note right of CheckUpListController
    - userEmail is obtained
    from the user session
    - categoryDescription
    is retrieved from selected data

end note

note bottom of VehicleRepository
    - used for displaying
    the vehicle list
end note

class CheckUpListUI {
}


Repositories -> "1" VehicleRepository
Repositories -> Repositories : instance

ApplicationSession -> ApplicationSession : instance
ApplicationSession --> "1" UserSession : userSession

CheckUpListUI .> CheckUpListController

CheckUpListController .> Repositories : repositories
CheckUpListController ..> ApplicationSession
CheckUpListController ..> UserSession
CheckUpListController ..> VehicleRepository : VehicleRepository
CheckUpListController ..> VehicleRepository : VehicleRepository

Vehicle --> Employee : createdBy

VehicleRepository "1" --> "*" Vehicle : vehicles

@enduml