@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant "checkUpListController\n:CheckUpListController" as VC
participant "vehicleRepository\n:VehicleRepository" as VehicleRepository

autonumber 16
-> VC: getCheckUpList()

autonumber 16.1
activate VC
    group Check-Up List

        VC -> VehicleRepository**: getCheckUpList()

        VehicleRepository -> VC : vehicleCheckUpList

    end

    autonumber 17
    <- VC : vehicleCheckUpList
deactivate VC


@enduml