@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "GSM" as GSM
participant ":System" as System

activate GSM

        GSM -> System : asks to know the exact costs referring to water consumption.
    activate System

     System --> GSM : requests data (CSV File)
    deactivate System

        GSM -> System : introduce requested data
    activate System

     System --> GSM : shows all data and requests confirmation
    deactivate System

        GSM -> System : confirms data
    activate System

     System --> GSM : displays operation success
     System --> GSM : displays Barplot success
     System --> GSM : displays Average of monthly costs
     System --> GSM : displays Histograms of 10 class's
    deactivate System

@enduml