@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox


participant ":RegisterSkillController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "skillRepository:\nSkillRepository" as skillRepository
participant "Skill:\nSkill" as Skill

autonumber 5
-> CTRL : registerSkill(skill name)





            activate CTRL
            CTRL -> CTRL : verifySkillName(skill name))


                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getSkillRepository()
                activate PLAT

                    PLAT --> CTRL: skillRepository
                deactivate PLAT


                activate skillRepository


                    CTRL -> skillRepository : registerSkill (skill name)

                    skillRepository -> Skill** : create()

                    skillRepository -> skillRepository : verifyIfExistAndSave(skill name)




                skillRepository -> CTRL : skillList

 autonumber 15
    <-- CTRL : skillName
            deactivate CTRL







@enduml