@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Register Vehicle Check-Up Success Scenario

autonumber

actor "FM" as FleetManager
participant ":System" as System

activate FleetManager

    FleetManager -> System : Selects a Vehicle ID and requests to register check-up
    activate System

    System --> FleetManager : Requests Date of Check-Up, Current Kilometers
    deactivate System

    FleetManager -> System : Provides Date of Check-Up, Current Kilometers 
    activate System

        System -> System : Validate Date of Check-Up
        System -> System : Validate Current Kilometers format

        System --> FleetManager : Confirms registration success
    deactivate System

@enduml
