@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox


participant ":AssignEntryOnAgendaController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "entryRepository\n:EntryRepository" as EntryRepository
participant ":Entry" as OBJ
participant ":EntryDto" as DTO
participant ":EntryMapper" as MAPPER
participant "toDoListDto : List<EntryDto>" as ListDTO
participant "toDoList : List<Entry>" as List

autonumber 3


'            UI --> CollaboratorUser : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL

            activate CTRL



            CTRL -> RepositorySingleton : getInstance()
        group Get Collaborator from session
                                                    activate RepositorySingleton

                                                        RepositorySingleton --> CTRL: repositories
                                                    deactivate RepositorySingleton

                                                    CTRL -> PLAT : getEntryRepository()
                                                    activate PLAT

                                                    PLAT -> CTRL : entryRepository
                                                    deactivate PLAT

                                                     CTRL -> PLAT : getCollaboratorRepository()
                                                              activate PLAT

                                                    PLAT -> CTRL : collaboratorRepository
                                                                deactivate PLAT

                                                                CTRL -> ApplicationSession : getInstance()
                                                                                                                              activate ApplicationSession

                                                                                                                    ApplicationSession -> CTRL : applicationSession
                                                                                                                                deactivate ApplicationSession




            CTRL -> CTRL : getCollaboratorFromSession()
            activate CTRL

            CTRL -> ApplicationSession : getCurrentSession()
            activate ApplicationSession

            ApplicationSession -> User : getUserEmail()
            activate User

            User-> ApplicationSession : email
            deactivate User

            ApplicationSession -> CTRL : email
            deactivate ApplicationSession
            deactivate CTRL

            CTRL -> CollabRepository : getCollaboratorByEmail()
            activate CollabRepository

            CollabRepository -> CTRL : collaborator

           deactivate CollabRepository

        end
























@enduml