@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class GreenSpace {
    -Enum Type
}



class greenSpaceRepository {

           + registerGreenSpace()
           + verifyIfExists()

}

class GreenSpaceMapper{

}

class GreenSpaceDTO{

}


class Repositories {
        - Repositories()
        + getInstance() : Repositories
        + getGreenSpaceRepository() : GreenSpaceRepository
}

class RegisterGreenSpaceController{
    - GreenSpaceRepository greenSpaceRepository
        + getGreenSpaceType()
        + registerGreenSpace()

}
GreenSpaceMapper "1" - "*" GreenSpaceDTO
GreenSpaceMapper "1" -- "*" GreenSpace

RegisterGreenSpaceController "1" -> "1" GreenSpaceMapper
greenSpaceRepository "1" --> "1" GreenSpaceMapper
RegisterGreenSpaceUI"1" --> "1" RegisterGreenSpaceController


RegisterGreenSpaceController .> Repositories : repositories


RegisterGreenSpaceController ..> GreenSpace
RegisterGreenSpaceController ..> greenSpaceRepository : greenSpaceRepository



Repositories -> Repositories : instance
Repositories -> "1" greenSpaceRepository

greenSpaceRepository "1" --> "*" GreenSpace : GreenSpaces




@enduml