@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as GSM
participant ":RegisterGreenSpaceUI" as UI
participant ":RegisterGreenSpaceController" as CTRL
participant ":Repositories" as Repos
participant "repositories\n:Repositories" as reposRepos
participant "organizationRepository:Organization" as Organization
participant ":GreenSpace" as GreenSpace
participant "<<enum>>\nGreenSpace.Type" as Type

participant "greenSpaceTypeListDto:list<GreenSpaceDTO>" as TypeListDto
participant "objDto:GreenSpaceDTO" as GreenDto




participant "greenSpace:GreenSpace" as obj





activate GSM

GSM -> UI : Asks to Register a New Green Space

activate UI

UI -> CTRL** : create()



UI -> CTRL: getGreenSpaceTypeListDto()
activate CTRL


CTRL -> Repos: getInstance()
activate Repos

Repos --> CTRL: repositories
deactivate Repos

CTRL -> reposRepos: getOrganizarionRepository()
activate reposRepos

reposRepos --> CTRL: organizarionRepository
deactivate reposRepos

CTRL -> Organization: getEnumGreenSpaceTypes()
activate Organization

Organization -> GreenSpace : getEnumGreenSpaceTypes()
activate GreenSpace

GreenSpace -> Type  : values()
activate Type


Type -> GreenSpace  : enumGreenSpaceTypes
deactivate Type

GreenSpace -> Organization  : enumGreenSpaceTypes

deactivate GreenSpace

Organization -> CTRL  : enumGreenSpaceTypes
deactivate Organization







CTRL --> UI : greenSpaceTypeListDto
deactivate CTRL


UI -> GSM : Displays all available green space types and requests\n the name, address, area, and type for the new green space
deactivate UI

GSM -> UI: Provides the name, address, area, and selects a green space type
activate UI

UI -> CTRL: registerGreenSpace(greenSpaceDto)
activate CTRL

note right of UI
(newName, newAddress,
 newArea, typeName)
end note

CTRL -> Organization : greenSpace = registerGreenSpace(greenSpaceDto)
activate Organization
note right of CTRL
(newName, newAddress, newArea, typeName)
end note


Organization -> GreenDto : greenSpace = toModel(greenSpaceDto)
activate GreenDto

note right of Organization
(newName, newAddress, newArea, typeName)
end note
deactivate GreenDto




Organization-> GreenDto : newName = getNameGreenSpace()
activate GreenDto 
deactivate GreenDto

Organization-> GreenDto : newAdress = getAdress()
activate GreenDto 
deactivate GreenDto

Organization-> GreenDto : newArea = getAreaInHectares()
activate GreenDto 
deactivate GreenDto

Organization -> GreenDto : newType = getType()
activate GreenDto 
deactivate GreenDto



Organization -> obj** : create(newName, newAddress, newArea, type)

activate obj

obj -> Organization : true
deactivate obj

Organization-> Organization: verifyIfExistAndSave(greenSpace)
deactivate GreenSpaceMapper

Organization -> CTRL : true
deactivate Organization


CTRL --> UI : true
deactivate CTRL


UI --> GSM : displays operation success
deactivate UI

deactivate GSM

@enduml