@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
participant ":RegisterGreenSpaceController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "greenSpaceRepository:\nGreenSpaceRepository" as greenSpaceRepository
participant ":GreenSpace" as classObj
participant "greenSpace:GreenSpace" as obj
autonumber 2

-> CTRL** : create()
activate CTRL
    group Get Green Space Type


                autonumber 2.1
                CTRL -> RepositorySingleton : getInstance()
                activate RepositorySingleton

                    RepositorySingleton --> CTRL: repositories
                deactivate RepositorySingleton

                CTRL -> PLAT : getGreenSpaceRepository()
                activate PLAT

                    PLAT --> CTRL: greenSpaceRepository
                deactivate PLAT




                CTRL -> classObj : getEnumGreenSpaceType()
                activate classObj

                classObj -> CTRL: greenSpaceTypes

                deactivate

                deactivate greenSpaceRepository

    end
    autonumber 3
<-- CTRL  :  greenSpaceTypes

@enduml