@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0

left to right direction

package "UI" #f0f0f0{
    class RegisterGreenSpaceUI {
    }

}
package "Core" #f0f0f0{

    package "Controller" #dddddd{

        class RegisterGreenSpaceController {
            +getGreenSpaceTypeListDto(objDto: TeamDto, entryDto: EntryDto)
        }

        RegisterGreenSpaceUI ..>  RegisterGreenSpaceController



@enduml

