@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
'skinparam shadowing false

left to right direction

rectangle "System Actors" as actors {
    actor "Fleet Manager" as Manager
    actor "Human Recourses Manager" as HRM
}


rectangle "Use Cases" as usecases{
    note right of Manager
        Who manage Machines, Vehicles and Equipment
    end note
    usecase "UC6 -  Register a vehicle including Brand, Model, Type, Tare, Gross Weight, Current Km,\n Register Date, Acquisition Date, Maintenance/Check-Up Frequency (in Kms)." as UC6
    Manager --> UC6

    usecase "UC7 - Register a vehicle's check-up" as UC7
    Manager --> UC7

    usecase "UC8 - List the vehicles needing the check-up" as UC8
    Manager --> UC8

    note right of HRM
        Who manage Collaborators, Teams, Skills and Jobs
    end note
    usecase "UC1 - Register skills that may be appointed to a collaborator" as UC1
    HRM --> UC1

    usecase "UC2 - Register a job" as UC2
    HRM --> UC2

    usecase "UC3 - Register a collaborator with a job and fundamental characteristics." as UC3
    HRM --> UC3

    usecase "UC4 - Assign one or more skill(s) to a collaborator" as UC4
    HRM --> UC4

    usecase "UC5 - Generate a team to proposal automatically." as UC5
    HRM --> UC5




}

@enduml