@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "GSM" as Manager
participant ":System" as System

activate Manager


ref over Manager : Get the details and management options\n of a selected entry on the agenda

Manager -> System : Asks to postpone an Entry

    activate System

        System --> Manager : Ask to introduce a new date and a new start hour
    deactivate System

   Manager  -> System : introduces requested data
    activate System

    System --> Manager : Confirms the change
    deactivate System



@enduml