@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "Collaborator" as Collaborator
participant ":System" as System

activate Collaborator

    Collaborator -> System : asks to view the tasks assigned to him
    activate System

        System --> Collaborator : shows tasks list and wait for option of sort or view task option
    deactivate System

@enduml