@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
'skinparam linetype ortho
'left to right direction
skinparam classAttributeIconSize 0
hide circle
hide methods
title Domain Model Green Spaces Software Management

'class Platform {
'  -description
'}

class Organization {
}

class Manager{
    name
}

class Task {
}


class HRM{
    name
    email
    password
}

class Skill{
    skillName
}

class VFM{
    email
    password
}

class GSM{
    email
    password
}

class Vehicle{
    plate
    brand
    model
    type
    tare
    grossWeight
    currentKm
    registerDate
    acquisitionDate
    maintenanceFrequency
}

class Agenda{
    greenSpace
    startDate
    finishDate
}

class Equipment{
    nameType
}

class Job{
    jobName
}

class Machine{
    nameType
}

class Team{
    skillSet
    size
}


class Collaborator {
    name
    birthdate
    admissionDate
    address
    mobileNumber
    email
    docType
    docNumber
}

Organization "1" -- "1..*" Manager : have >

Manager "1" -- "1" HRM : has >
Manager "1" -- "1" VFM : has >
Manager "1" -- "1" GSM : has >

HRM "1" -- "0..*" Colaborator : register >
HRM "1" -- "0..*" Job : has >
HRM "1" -- "0..*" Team : creates >
HRM "1" -- "0..*" Skill : creates >

VFM "1" -- "0..*" Vehicle : manage >
VFM "1" -- "0..*" Equipment : manage >
VFM "1" -- "0..*" Machine : manage >
VFM "1" -- "0..*" Vehicle : manages >

GSM "1" --- "0..*" Colaborator : manage >
GSM "1" --- "0..*" Vehicle : manage >
GSM "1" --- "0..*" Team : manage >
GSM "1" --- "0..*" Task : create >
GSM "1" --- "0..*" Equipment : manage >
GSM "1" --- "0..*" Job : manage >
GSM "1" --- "0..*" Machine : manage >
GSM "1" - "0..*" Agenda : manage >
GSM "1" --- "0..*" Skill : manage >

Vehicle "1" -- "0..*" Task : has >

Equipment "1" -- "0..*" Task : has >

Collaborator "0..*" -- "0..*" Skill : posesses >
Collaborator "1" -- "0..*" Team : has >

Job "1" -- "0..*" Collaborator : has >

Team "1" -- "1" Task : has >
Team "1" -- "1" Agenda : has >

Machine "1" -- "0..*" Team : has >


Agenda "1" -- "0..*" Team : has >
Agenda "1" -- "0..*" Task : have >




@enduml