@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "HR Manager" as HRManager
participant "AssignTeamEntryAgendaUI" as UI
participant ":AssignTeamEntryController" as Controller

participant "Repositories" as Repos
participant "repositories:Repositories" as reposRepos
participant "TeamRepository:TeamRepository" as TeamRepo
participant "entryRepository:EntryRepository" as EntryRepo

participant "entry:Entry" as Entry

participant ":EmailService" as EmailService

participant ":ApplicationSession" as ApplicationSession
participant ":GmailService" as GmailService
participant ":DeiEmailService" as DeiEmailService
activate HRManager

HRManager -> UI : Asks to assign a Team to an Entry in the Agenda
activate UI

UI -> Controller** : create

UI -> Controller : getCollaboratorNames()
activate Controller

Controller -> Repos : getInstance()
activate Repos

Repos --> Controller : repositories
deactivate Repos

Controller -> reposRepos : getSkillRepository()
activate reposRepos

reposRepos --> Controller : skillRepository
deactivate reposRepos

Controller -> reposRepos : getCollaboratorRepository()
activate reposRepos

reposRepos --> Controller : collaboratorRepository
deactivate reposRepos

Controller -> reposRepos : getEntryRepository()
activate reposRepos

reposRepos --> Controller : EntryRepository
deactivate reposRepos

Controller -> TeamRepo : getTeamsList()
activate TeamRepo

TeamRepo --> Controller : TeamsList
deactivate TeamRepo


Controller -> EntryRepo : getAgendaEntriesList()
activate EntryRepo

EntryRepo --> Controller : AgendaEntriesList
deactivate EntryRepo

Controller -> UI : EntriesNames, TeamsNames
deactivate Controller

UI -> HRManager : Shows Names of Teams and Agenda Entries
deactivate UI

HRManager -> UI : Selects Team and Assigns to an Agenda Entry
activate UI

UI -> Controller : assignTeamToEntry(teamName, agendaName)
activate Controller

Controller -> EntryRepo : assignTeamToEntry(teamName, agendaName)
activate EntryRepo

EntryRepo -> TeamRepo : findTeamByName(teamName)
activate TeamRepo

TeamRepo -> EntryRepo  : team
deactivate TeamRepo

EntryRepo -> EntryRepo : findEntryByName(entryName)
activate EntryRepo
deactivate EntryRepo
EntryRepo -> Entry : assignTeam(team)
activate Entry

loop for each collaborator in collaboratorsTeam
    Entry -> EmailService: sendToEmailFile(collaborator.getEmail(), subject, message);
    activate EmailService
    EmailService -> ApplicationSession : getEmailService()
    activate ApplicationSession


    ApplicationSession --> EmailService : emailService
    deactivate ApplicationSession

    alt emailService is GmailService
        EmailService -> GmailService : sendEmail(member.getEmail(), "Assignment Notification", "You have been assigned to an entry in the agenda.")
        activate GmailService
        deactivate GmailService
    else emailService is DeiEmailService
        EmailService -> DeiEmailService : sendEmail(member.getEmail(), "Assignment Notification", "You have been assigned to an entry in the agenda.")
        activate DeiEmailService
        deactivate DeiEmailService

    end
end
deactivate EmailService


Entry --> EntryRepo : true
deactivate Entry


EntryRepo --> Controller : true
deactivate EntryRepo


Controller --> UI : true
deactivate Controller

UI --> HRManager : Displays Operation Success Message
deactivate UI

@enduml
