@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0

left to right direction

package "UI" #f0f0f0{
    class ViewDetailsEntryAgendaUI {
    }

    class AssignTeamUI {
        +setEntry(entryDto: EntryDto): void
    }
}

package "Core" #f0f0f0{

package "Adapters" #ddd {
    class EmailService {
        +sendEmailToCollaborator(collaborator: Collaborator, entryDto: EntryDto): void
        +sendEmail(to: String, subject: String, body: String): void
        +sendToEmailFile(to: String, subject: String, body: String): void
    }

    class DeiEmailService implements SendEmailExternalAPI {
        +sendEmail(to: String, subject: String, body: String): void
    }

    class GmailService implements SendEmailExternalAPI {
        +sendEmail(to: String, subject: String, body: String): void
    }

    interface SendEmailExternalAPI{
        +sendEmail(to: String, subject: String, body: String): void
    }
}   


package "Session" #ddd {
    class ApplicationSession {
        - instance: ApplicationSession
        + getInstance(): ApplicationSession
        + getEmailServiceInstance(): EmailService
    }
}

    package "Controller" #dddddd{

        class ViewDetailsEntryController {
            +getTeamListPossibleForEntry(entryDto: EntryDto): List<TeamDto>
            +assignTeamToEntry(teamDto: TeamDto, entryDto: EntryDto): void
        }

    }

    package "Mapper" #dddddd{

            class TeamMapper {
                +teamListToTeamDtoList(teamList: List<Team>): List<TeamDto>
            }

            class EntryMapper {
                +entryDtoToEntry(entryDto: EntryDto, entry: Entry): Entry
                +shouldUpdateTeamOrVehicles(entry: Entry, entryDto: EntryDto): boolean
                +updateTeamAndVehicles(entry: Entry, entryDto: EntryDto): void
            }
        }

        package "DTO" #dddddd{

            class EntryDto {
                +startDate: Date
                +status: String
                +teamAssigned: TeamDto
                +reference: String
                +finishDate: Date
                + assignTeam(teamDto: TeamDto)
            }

            class TeamDto {
                +teamName: String
                +members: List<Collaborator>
            }
        }

    package "Domain" #dddddd{

    
        package "Repository" #bbbbbb{

            class Repositories {
                - entryRepository: EntryRepository
                - teamRepository: TeamRepository
                - static instance: Repositories
                + getInstance(): Repositories
                + getEntryRepository(): EntryRepository
                + getTeamRepository(): TeamRepository
                - Repositories()
            }

            class EntryRepository {
                - agenda: AgendaList
                + getAgenda(): AgendaList
                + assignTeamOnEntry(entryDto: EntryDto): Optional<Entry>
                + searchForEntryAgenda(entryDto: EntryDto): Entry
            }

            class TeamRepository {
                + getTeams(): List<Team>
            }

            package "Lists" #999{
                class AgendaList {
                    + filterTeamNotActivateInTime(teamList: List<Team>, entryDto: EntryDto): List<Team>
                }
            }
        }

        package "Model" #bbbbbb{

            class Entry {
                +reference: String
                +status: String
                +startDate: Date
                +teamAssigned: Team
                +finishDate: Date
                +description: String
                +title: String
                +getTeamAssigned(): TeamDto
            }

            class Team {
                +teamName: String
                +members: List<Collaborator>
            }

            class Collaborator {
                +name: String
                +email: String
            }
        }
    }
}


ViewDetailsEntryAgendaUI ..> AssignTeamUI
AssignTeamUI ..> ViewDetailsEntryController
ViewDetailsEntryController ..> Repositories : repositories
ViewDetailsEntryController ..> EntryRepository : entryRepository
ViewDetailsEntryController ..> TeamRepository : teamRepository
ViewDetailsEntryController ..> AgendaList : agendaList
ViewDetailsEntryController ..> TeamMapper 
ViewDetailsEntryController ..> EntryDto 
EntryRepository ..> EntryMapper
ViewDetailsEntryController ..> TeamDto 
ViewDetailsEntryController ..> EmailService
EmailService ..> Collaborator
EmailService ..> Entry
EmailService ..> ApplicationSession
EmailService ..> DeiEmailService
EmailService ..> GmailService

TeamRepository "1" --> "*" Team
EntryRepository "1" --> "*" Entry
Repositories "1" --> "1" TeamRepository
Repositories "1" --> "1" EntryRepository
AgendaList "1" --> "*" Entry
EntryMapper ..> EntryDto
TeamMapper ..> TeamDto

@enduml
