@startuml
!pragma teoz true
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as Actor

participant ":ViewDetailsEntryAgendaUI" as UI
participant "AssignTeamUI" as UI2



participant ":ViewDetailsEntryController" as CTRL2
participant "Repositories" as Repos
participant "repositories\n:Repositories" as reposRepos
participant "entryRepository:EntryRepository" as EntryRepo
participant "teamRepository:TeamRepository" as TeamRepo
participant "agendaList:AgendaList" as AgendaList
participant ":TeamMapper" as TeamMapper
participant ":EntryMapper" as EntryMapper


participant "teamListFiltered:list<Team>" as TeamList
participant "teamListDto:List<TeamDto>" as TeamListDto
participant "objDto:TeamDto" as TeamDto
participant "entryDto:EntryDto" as EntryDto

participant ":EmailService" as EmailService
participant "entry:Entry" as Entry
participant "collaborator:Collaborator" as Collaborator
participant "someEmailService: SomeEmailService\nimplements <<SendEmailExternalAPI>>" as SomeEmailService

participant "ApplicationSession" as Session
participant "applicationSession:ApplicationSession" as ApplicationSession

activate Actor

ref over Actor : Get details and management options\n of a selected entry on the agenda


Actor -> UI : Asks to Assign a Team to the Selected Entry
activate UI

UI -> UI2 :setEntry(entryDto)
activate UI2
deactivate UI

UI2 -> CTRL2 : getTeamListPossibleForEntry(entryDto)
activate CTRL2


    CTRL2 -> Repos: getInstance()
    activate Repos

    Repos --> CTRL2: repositories
    deactivate Repos

    CTRL2 -> reposRepos: getEntryRepository()
    activate reposRepos

    reposRepos --> CTRL2: entryRepository
    deactivate reposRepos

    CTRL2 -> reposRepos: getTeamRepository()
    activate reposRepos

    reposRepos --> CTRL2: teamRepository
    deactivate reposRepos

CTRL2 -> EntryRepo: getAgenda()
activate EntryRepo

EntryRepo -> CTRL2: agendaList
deactivate EntryRepo

CTRL2 -> TeamRepo: teamList = getTeams()
activate TeamRepo
deactivate TeamRepo


CTRL2 -> AgendaList: filterTeamNotActivateInTime(teamList,entryDto)
activate AgendaList

AgendaList -> CTRL2 :  teamListFiltered
deactivate AgendaList

CTRL2 -> TeamMapper: teamListToTeamDtoList(teamListFiltered)
activate TeamMapper


TeamMapper -> TeamListDto** : create()

loop for each object in TeamListFiltered
    TeamMapper -> TeamList : obj = get()
    activate TeamList
    deactivate TeamList
    TeamMapper -> TeamMapper: objDto = toDto(obj)
    activate TeamMapper

    TeamMapper -> TeamDto** : create(objAllAtributes)
    deactivate TeamMapper
    TeamMapper -> TeamListDto : add(objDto)
    activate TeamListDto
    deactivate TeamListDto
end

TeamMapper -> CTRL2 : teamListDto
deactivate TeamMapper

CTRL2 -> UI2  : teamListDtoPossible
deactivate CTRL2



UI2 -> Actor : Shows possible Teams for Entry Assignment List
deactivate UI2

Actor -> UI2 : Selects a team and Assigns it to the selected entry
activate UI2

UI2 -> CTRL2 : assignTeamToEntry(teamDto, entryDto)
activate CTRL2

CTRL2 -> EntryDto : assignTeam(teamDto)
activate EntryDto
EntryDto -> EntryDto : teamAssigned = teamDto
||0||
deactivate EntryDto


CTRL2 -> EntryRepo : assignTeamOnEntry(entryDto)


activate EntryRepo

EntryRepo -> EntryRepo : entry = searchForEntryAgenda(entryDto)
EntryRepo -> EntryMapper : entryDtoToEntry(entryDto, entry)
activate EntryMapper
EntryMapper -> EntryMapper: shouldUpdateTeamOrVehicles\n = shouldUpdateTeamOrVehicles(entry, entryDto)
note right of EntryMapper
     "shouldUpdateTeamOrVehicles" verifies if the team or vehicles in the entry need to be updated based on the changes in entryDto.
end note
alt shouldUpdateTeamOrVehicles is true
    EntryMapper -> EntryMapper : updateTeamAndVehicles(entry, entryDto)
    activate EntryMapper

    alt teamAssigned in entryDto is not null
        EntryMapper -> Entry : teamAssigned = getTeamAssigned()
        activate Entry
        deactivate Entry
        deactivate EntryMapper
    end

    deactivate EntryMapper
end



EntryRepo -> CTRL2 : Optional<Entry>
deactivate EntryRepo


alt Optional<Entry> is present, i.e\n Entry was successfully assigned
    CTRL2 -> TeamDto : getTeamList()
    activate TeamDto
    TeamDto -> CTRL2 : collaboratorsList
    deactivate TeamDto
    
    CTRL2 -> EmailService : sendEmailToList(collaboratorsList, entryDto)
    activate EmailService
    loop for each collaborator in collaboratorsList
        EmailService -> Collaborator : to = getEmail() 
        activate Collaborator
        deactivate Collaborator

        EmailService -> Entry : subject = getTitle() 
        activate Entry
        deactivate Entry

        EmailService -> Entry : description = getDescription() 
        activate Entry
        deactivate Entry

        EmailService -> Entry : teamAssigned = getTeamAssigned() 
        activate Entry
        deactivate Entry

        EmailService -> EmailService : body = description + teamAssigned 

        EmailService -> EmailService : sendToEmailFile(to, subject, body)


        EmailService -> Session : getInstance()
        activate Session

        Session --> EmailService : applicationSession
        deactivate Session

        EmailService --> ApplicationSession : getEmailServiceInstance()
        activate ApplicationSession

        ApplicationSession --> EmailService : someEmailService
        deactivate ApplicationSession

        EmailService -->  SomeEmailService : sendEmail(to, subject, body)
        activate SomeEmailService
        deactivate SomeEmailService
        deactivate EmailService



    end
    
    CTRL2 -> UI2 : true
else
    CTRL2 -> UI2 : false
    deactivate CTRL2
end



UI2 --> Actor : Displays Operation Success Message
deactivate UI2
@enduml
