@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as GSM

participant ":ViewDetailsEntryUI" as UI2
participant ":ViewDetailsEntryController" as CTRL2


participant "entryRepository:EntryRepository" as EntryRepo


participant ":EntryMapper" as EntryMapper
participant "entryDto:EntryDto" as EntryDto

participant "TeamRepository:TeamRepository" as TeamRepo

participant ":TeamMapper" as TeamMapper
participant "objDto:TeamDto" as TeamDto




participant "entry:Entry" as Entry

participant ":EmailService" as EmailService

participant ":ApplicationSession" as ApplicationSession
participant ":GmailService" as GmailService
participant ":DeiEmailService" as DeiEmailService

activate GSM
activate UI2
activate CTRL2

ref over GSM : Get details and management options\n of a selected entry on the agenda

note right of UI2
    UI and Controller were activated simultaneously with GSM,
    because this diagram continues from the previous one referenced
    in this diagram at the beggining.
end note

GSM -> UI2 : Selects a Team and Assigns it to the Selected Entry


UI2 -> CTRL2 : assignTeamToEntry(objDto, entryDto)
note right of UI2
   Remember that in the previous diagram, 
   ViewDetailsUI received entryDto from AgendaUI via 
   receiveDto and will use it via this method: "assignTeamToEntry"
end note
note right of UI2
    {teamName}, entry
end note


CTRL2 -> TeamRepo : getTeamName(objDto)
note right of CTRL2
    teamName
end note
activate TeamRepo

TeamRepo -> TeamMapper : extractName(objDto)
note right of TeamRepo
    teamName
end note
activate TeamMapper

TeamMapper -> TeamDto : teamName = getTeamName()
activate TeamDto
deactivate TeamDto

TeamMapper -> TeamRepo : teamName
deactivate TeamMapper

TeamRepo -> CTRL2 : teamName
deactivate TeamRepo


CTRL2 -> TeamRepo : findTeamByName(teamName)
activate TeamRepo

TeamRepo -> CTRL2  : team
deactivate TeamRepo


CTRL2 -> EntryRepo : assignTeamToEntry(team, entryDto)

activate EntryRepo

EntryRepo -> EntryMapper : toDomainAndAssignTeam(team, entryDto)

activate EntryMapper

EntryMapper -> EntryDto : reference = getReference()
activate EntryDto
deactivate EntryDto

EntryMapper -> EntryRepo : findEntryByReference(reference)
activate EntryRepo

EntryRepo -> EntryMapper : entry

deactivate EntryRepo


EntryMapper -> Entry : assignTeam(team)
activate Entry

loop for each collaborator in collaboratorsTeam
    Entry -> EmailService: sendToEmailFile(collaborator.getEmail(), subject, message);
    activate EmailService
    EmailService -> ApplicationSession : getEmailService()
    activate ApplicationSession


    ApplicationSession --> EmailService : emailService
    deactivate ApplicationSession

    alt emailService is GmailService
        EmailService -> GmailService : sendEmail(member.getEmail(), "Assignment Notification", "You have been assigned to an entry in the agenda.")
        activate GmailService
        deactivate GmailService
    else emailService is DeiEmailService
        EmailService -> DeiEmailService : sendEmail(member.getEmail(), "Assignment Notification", "You have been assigned to an entry in the agenda.")
        activate DeiEmailService
        deactivate DeiEmailService

    end
end
deactivate EmailService

Entry --> EntryMapper : true
deactivate Entry

EntryMapper --> EntryRepo : true
deactivate EntryMapper


EntryRepo --> CTRL2 : true
deactivate EntryRepo


CTRL2 --> UI2 : true
deactivate CTRL2

UI2 --> GSM : Displays Operation Success Message
deactivate UI2

@enduml
