@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber



participant ":ViewDetailsEntryController" as CTRL2

participant "objDto:TeamDto" as TeamDto 
participant ":EmailService" as EmailService
participant "entry:Entry" as Entry
participant "collaborator:Collaborator" as Collaborator
participant "someEmailService: SomeEmailService\nimplements <<SendEmailExternalAPI>>" as SomeEmailService

participant "ApplicationSession" as Session
participant "applicationSession:ApplicationSession" as ApplicationSession



-> CTRL2: Optional<Entry>

autonumber 16.1
activate CTRL2

group Send Email To All Team Members
    CTRL2 -> TeamDto : getTeamList()
    activate TeamDto
    TeamDto -> CTRL2 : collaboratorsList
    deactivate TeamDto

    CTRL2 -> EmailService : sendEmailToList(collaboratorsList, entryDto)
    activate EmailService
    loop for each collaborator in collaboratorsList
        EmailService -> Collaborator : to = getEmail()
        activate Collaborator
        deactivate Collaborator

        EmailService -> Entry : subject = getTitle()
        activate Entry
        deactivate Entry

        EmailService -> Entry : description = getDescription()
        activate Entry
        deactivate Entry

        EmailService -> Entry : teamAssigned = getTeamAssigned()
        activate Entry
        deactivate Entry

        EmailService -> EmailService : body = description + teamAssigned

        EmailService -> EmailService : sendToEmailFile(to, subject, body)


        EmailService -> Session : getInstance()
        activate Session

        Session --> EmailService : applicationSession
        deactivate Session

        EmailService --> ApplicationSession : getEmailServiceInstance()
        activate ApplicationSession

        ApplicationSession --> EmailService : someEmailService
        deactivate ApplicationSession

        EmailService -->  SomeEmailService : sendEmail(to, subject, body)
        activate SomeEmailService
        deactivate SomeEmailService
        deactivate EmailService

    end
end

autonumber 17

<-- CTRL2  : true
deactivate CTRL2

@enduml
