@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline

skinparam classAttributeIconSize 0

class Repositories {
    - static instance : Repositories
    - vehicleRepository : VehicleRepository
    + getInstance() : Repositories
    + getVehicleRepository() : VehicleRepository
    - Repositories()
}

class VehicleRepository {
    - vehicleList : List<Vehicle>
    + addVehicle(vehicle : Vehicle)
    + getVehiclePlateList() : List<String>
    + addCheckUp(plate : String, dateAsString : String, currentKms : double, maintenanceKm: double) : boolean
    + findVehicleByPlate(plate : String) : Vehicle
    + convertStringToDate(dateAsString : String) : Date
    + getCheckUpDetailsList(plate : String) : List<String>
    + getLastKmForVehicle(plate : String) : int
}

class RegisterCheckUpUI {
    - controller : RegisterCheckUpController
    + startCheckUpProcess()
    + processCheckUpRegistration()
    + displayPlatesList(plates : List<String>)
    + verifyCheckUpDateFormat(date : String) : boolean
    + verifyKilometersFormat(kms : String) : boolean
}

class RegisterCheckUpController {
    - repositories : Repositories
    + RegisterCheckUpController()
    + getDataNeededToRegisterCheckUp() : List<String>
    + validateCheckUpDate(date : String) : boolean
    + validateKilometers(kms : double, plate : String) : boolean
    + addCheckUp(plate : String, date : String, currentKms : double, maintenanceKm: double) : List<String>
}

class Vehicle {
    - plate : String
    - currentKm : double
    - frequencyCheckKm : double
    - checkUpList : List<CheckUp>
    + addCheckUp(km : double, date : Date)
    + getVehicleCheck UpDetailsList() : List<String>
    + getCurrentKm() : double
    + getPlate() : String
}

class CheckUp {
    - kmOfCheck : double
    - dateOfCheck : Date
    + getDateOfCheck() : Date
    + getKmOfCheck() : double
}

RegisterCheckUpUI ..> RegisterCheckUpController
RegisterCheckUpController ..> Repositories: repositories
Repositories "1" *-- "1" VehicleRepository
VehicleRepository "1" o-- "*" Vehicle
Vehicle "1" *-- "*" CheckUp

@enduml
