@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) for Registering Vehicle Maintenance

autonumber

actor "VFM" as FleetManager


participant ":RegisterCheckUpUI" as UI
participant ":RegistMaintenanceController" as Controller

participant "Repositories" as Repos
participant "repositories:Repositories" as Repo
participant "vehicleRepository:VehicleRepository" as VehicleRepo
participant "collaboratorRepository:CollaboratorRepository" as CollabRepo


participant "vfm:VFM" as VFM
participant "vehicle:Vehicle" as Vehicle
participant "checkup:Checkup" as Checkup

activate FleetManager


FleetManager -> UI : Asks to register a maintenance
activate UI

UI -> Controller** : create

UI -> Controller : getDataNeededToRegisterCheckUp()
activate Controller

Controller -> Repos : getInstance()
activate Repos

Repos --> Controller : repositories
deactivate Repos        

Controller -> Repo : getVehicleRepository()
activate Repo
Repo --> Controller : vehicleRepository
deactivate Repo

Controller -> VehicleRepo : getVehiclePLateList()
activate VehicleRepo

VehicleRepo --> Controller : plates
deactivate VehicleRepo

Controller --> UI : vehiclePlates
deactivate Controller

UI --> FleetManager : Displays Plates list and Requests Date of Maintenande and Current Kilometers
deactivate UI

FleetManager -> UI : Selects a Plate, Provides Date of Maintenance and Current Kilometers and Submits
activate UI

UI -> UI : verifyCheckUpDateFormat(date)
UI -> Controller : validateCheckUpDate(date)
activate Controller

Controller -> UI : true
deactivate Controller

UI -> UI : verifyKilometersFormat(currentKms)

UI -> Controller : validateKilometers(currentKms, selectedPlate)
activate Controller

Controller -> UI : true
deactivate Controller

UI -> Controller : addCheckUp(selectedPlate, date, currentKms)
activate Controller
Controller -> VehicleRepo : addCheckUp(plate, date, currentKms)
activate VehicleRepo

VehicleRepo -> Vehicle : findVehicleByPlate(plate)
activate Vehicle

Vehicle -> VehicleRepo : vehicle
deactivate Vehicle

VehicleRepo -> Vehicle : addCheckUp(currentKms, date)
activate Vehicle
Vehicle -> Checkup** : new CheckUp(km, date)
activate Checkup

Checkup -> Vehicle : Created and Added to the Check Up List of the Vehicle which was under maintenance 
deactivate Checkup

Vehicle --> VehicleRepo : Done
deactivate Vehicle

VehicleRepo --> Controller : true
deactivate VehicleRepo

Controller -> UI : Success
deactivate Controller

UI --> FleetManager : Confirms registration success
deactivate UI

@enduml
