@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) for Registering Vehicle Maintenance

autonumber

actor "VFM" as FleetManager


participant ":RegistMaintenanceUI" as UI
participant ":RegistMaintenanceController" as Controller

participant "Repositories" as Repos
participant "repositories:Repositories" as Repo
participant "vehicleRepository:VehicleRepository" as VehicleRepo
participant "collaboratorRepository:CollaboratorRepository" as CollabRepo


participant "vfm:VFM" as VFM
participant "vehicle:Vehicle" as Vehicle
participant "checkup:Checkup" as Checkup

activate FleetManager


FleetManager -> UI : Asks to register a maintenance
activate UI

UI -> Controller** : create
activate Controller

Controller -> Repos : getInstance()
activate Repos

Repos --> Controller : repositories
deactivate Repos

Controller -> Repo : getCollaboratorRepository()
activate Repo
Repo --> Controller : collaboratorRepository
deactivate Repo

Controller -> CollabRepo : checkVFManager(userEmail)
activate CollabRepo

CollabRepo -> VFM : isVFM(userEmail)
activate VFM

VFM --> CollabRepo  : Authorization Status (true/false)
deactivate VFM

CollabRepo --> Controller  : Authorization Status (true/false)
deactivate CollabRepo

alt Authorization Status is False
    Controller --> UI : Not Authorized
    deactivate Controller

    UI --> FleetManager : Display Not Authorized Message
    deactivate UI
else Authorization Status is True

    Controller --> UI : Authorized
    activate UI
    activate Controller
    UI -> Controller : getVehiclePLateList()
    
    Controller -> Repo : getVehicleRepository()
    activate Repo
    Repo --> Controller : vehicleRepository
    deactivate Repo

    Controller -> VehicleRepo : fetchVehiclePLates()
    activate VehicleRepo

    VehicleRepo --> Controller : Vehicle Plates List
    deactivate VehicleRepo

    Controller --> UI : Displays Plates list and Requests Date of Maintenande and Current Kilometers
    deactivate Controller
   
    UI --> FleetManager : Displays Plates list
    deactivate UI

    FleetManager -> UI : Selects a Vehicle ID (Plate), Provides Date of Maintenance and Current Kilometers and Submits

    activate UI
    UI -> UI : Verify Date of Maintenance Format and Validate Date of Maintenance inserted
    UI -> UI : Verify Current Kilometers Format and Validate Current Kilometers inserted 

    alt Date Greater Or Equal To The Current (Valid) and Current Kilometers Value Inputed Greater Than the Last Current Kilometers Stored
        UI -> Controller : addMaintenance(Plate, Date, CurrentKms) 
        activate Controller
        Controller -> VehicleRepo : addMaintenance(Plate, Date, CurrentKms)
        activate VehicleRepo
        VehicleRepo -> Vehicle : updateVehicleMaintenanceList(Date, CurrentKms)
        activate Vehicle
        Vehicle -> Checkup** : createCheckup(Date, CurrentKms)
        activate Checkup
        Checkup -> Vehicle : Success (true)
        deactivate Checkup
        Vehicle --> VehicleRepo : Success (true)
        deactivate Vehicle
        VehicleRepo --> Controller : Success (true)
        deactivate VehicleRepo
        Controller --> UI : Success (true)
        deactivate Controller
        UI --> FleetManager : Confirms registration success
        deactivate UI
        
    else else
        UI -> FleetManager : Shows error, invalid input 
    end
end

@enduml
