@startuml

'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

class RegistMaintenanceUI {
}

class RegistMaintenanceController {
    + displayNotAuthorizedMessage()
    + displayPlatesList(platesList : List<String>)
    + displayInputError()
    + confirmRegistrationSuccess()
    + getVehiclePlateList()
    + verifyDateOfMaintenanceFormat(date : Date) : boolean
    + verifyCurrentKilometersFormat(kms : int) : boolean
    + getVehiclePlateList() : List<String>
}

class Repositories {
    + getInstance() : Repositories
    + getVehicleRepository() : VehicleRepository
    + getCollaboratorRepository() : CollaboratorRepository
}

class VehicleRepository {
    + fetchVehiclePlates() : List<String>
    + addMaintenance(plate : String, date : Date, currentKms : int) : boolean
    + updateVehicleMaintenanceList(date : Date, currentKms : int) : boolean
}

class CollaboratorRepository {
    + checkVFManager(userEmail : String) : boolean
}

class VFM {
    + isVFM(userEmail : String) : boolean
}

class Vehicle {
    - plate : String
    - maintenanceList : List<Checkup>
    + updateVehicleMaintenanceList(date : Date, currentKms : int) : boolean
}

class Checkup {
    - date : Date
    - currentKms : int
    + createCheckup(date : Date, currentKms : int) : Checkup
}

RegistMaintenanceUI "1" --> "1" RegistMaintenanceController
RegistMaintenanceController "1"  --> "1"  Repositories
RegistMaintenanceController "1"  --> "1"  VehicleRepository
RegistMaintenanceController "1"  --> "1"  CollaboratorRepository
Repositories "1" --> "1"  VehicleRepository
Repositories "1" --> "1" CollaboratorRepository
Repositories "1" --> "1"  Repositories

VehicleRepository "1" o-- "*" Vehicle
Vehicle "1" *-- "*" Checkup
CollaboratorRepository "1" o-- "*" VFM

@enduml
