@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "HRM" as HRManager
participant ":System" as System

activate HRManager

HRManager -> System : Selects Employee ID
activate System

System --> HRManager :  Validates employee ID and displays all skills already assigned to that employee
deactivate System

HRManager -> System : Selects Skill Name(s) to assign
activate System

System --> HRManager : Confirms skill assignment is possible
deactivate System

HRManager -> System : Confirms skill assignment
activate System

System -> System : Assigns Skill(s) to Collaborator
System --> HRManager : Displays operation success message

deactivate System
@enduml
