@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}

class GSM {
name
email
password
}

class GreenSpace {
EnumType{Garden
Large-sized park
Medium-sized park}

name
address
areaInHectares
}



'Platform "1" -- "*" Organization : has registered >
'Platform "1" -- "*" Category : defines >
GSM "1" -- "0..*" GreenSpace : Register >
@enduml