@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as GSM
participant ":RegisterTaskUI" as UI
participant ":RegisterTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "Organization\n:Organization" as Organization
participant "entryRepository:\nEntryRepository" as EntryRepository
participant "Task:\nTask" as Task
participant ":GreenSpaceDto" as DTO
participant ":GreenSpaceMapper" as MAPPER
participant "greenSpaceListDto : List<GreenSpaceDto>" as ListDTO
participant "List : List<GreenSpace>" as List
participant "entryDto: EntryDto" as EntryDto
participant ":Entry" as OBJ




activate GSM

        GSM -> UI : ask to add a new entry to the To-Do List
        activate UI

        UI -> CTRL** : createRegisterTaskController()
        activate CTRL

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT: getEntryRepository()
        activate PLAT

        PLAT --> CTRL: entryRepository
        deactivate PLAT


        CTRL -> Organization: getGreenSpaceList()
        activate Organization

        Organization -> List: getGreenSpaceList()
        activate List
        deactivate List

        Organization --> CTRL: greenSpaceList
        deactivate Organization

        CTRL -> MAPPER: toDto(greenSpaceList)
        activate MAPPER

        MAPPER -> ListDTO** : create()

        MAPPER -> List : greenSpace = getGreenSpace()
        activate List
        deactivate List

        MAPPER -> MAPPER : greenSpaceDto = toDTO(greenSpace)
        activate MAPPER

        MAPPER -> DTO**  : create(...)
        deactivate MAPPER

        MAPPER -> ListDTO : add(greenSpaceDto)
        activate ListDTO
        deactivate ListDTO

        MAPPER --> CTRL : greenSpaceListDto
        deactivate MAPPER

        CTRL --> UI: greenSpaceListDto

        UI --> GSM: show greenspace list and ask to select one

        GSM -> UI: selects green space

        UI -> CTRL : getDegreOfUrgency()


            CTRL -> Task: getDegreeUrgency()
        activate Task


        Task --> CTRL: degreeUrgency
        deactivate Task

        CTRL --> UI: degreeUrgency

        UI --> GSM: show degree of urgency list and ask to select one

        GSM -> UI: selects the urgency degree

        UI --> GSM: requests data (expected duration)

        GSM -> UI: types data

        UI --> GSM: show data and request confirmation

        GSM -> UI: confirms data

        UI -> CTRL: registerNewTask(entryDto)

        CTRL -> EntryRepository: registerNewTask(entryDto)
        activate EntryRepository

        EntryRepository -> EntryDto**: registerNewTask(entryDto)
        deactivate EntryRepository
        activate EntryDto

        EntryDto -> OBJ: status = setStatus()
        activate OBJ

        OBJ --> EntryDto: stateOfEntry

        EntryDto -> OBJ: greenSpaceDto = setGreenSpaceDto()

        OBJ --> EntryDto: greenSpace

        EntryDto -> OBJ: title = setTitle()

        OBJ --> EntryDto: title

        EntryDto -> OBJ: description = setDescription()

        OBJ --> EntryDto: description

        EntryDto -> OBJ: expectedDuration = setExpectedDuration()

        OBJ --> EntryDto: expectedDuration

        EntryDto -> OBJ: degreeUrgency = setDegreeUrgency()

        OBJ --> EntryDto: degreeOfUrgency

        EntryDto -> OBJ: startDate = setStartDate()

        OBJ --> EntryDto: startDate
        deactivate OBJ

        EntryDto --> EntryRepository: true/false
        activate EntryRepository

        EntryRepository --> CTRL: true/false
        deactivate EntryRepository

        CTRL --> UI: true/false

        UI --> GSM : displays operation success


        deactivate UI
        deactivate GSM

@enduml