@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as GSM
participant ":RegisterTaskUI" as UI
participant ":RegisterTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "GreenSpaceRepositories\n:GreenSpaceRepositories" as GreenSpaceRepositories
participant "entryRepository:\nEntryRepository" as EntryRepository
participant "GreenSpace\n:GreenSpace" as GreenSpace
participant "Task:\nTask" as Task
participant ":Entry" as OBJ
participant ":GreenSpaceDto" as DTO
participant ":GreenSpaceMapper" as MAPPER
participant "greenSpaceListDto : List<GreenSpaceDto>" as ListDTO
participant "List : List<GreenSpace>" as List
participant "entryDto: EntryDto" as EntryDto


activate GSM

        GSM -> UI : ask to add a new entry to the To-Do List
        activate UI

        UI -> CTRL** : create()
        activate CTRL

        CTRL -> RepositorySingleton : getInstance()
        activate RepositorySingleton

        RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT: getEntryRepository()
        activate PLAT

        PLAT --> CTRL: entryRepository
        deactivate PLAT

        CTRL -> PLAT: getGreenSpaceRepositories()
        activate PLAT

        PLAT --> CTRL: greenSpaceRepository
        deactivate PLAT

        CTRL -> GreenSpaceRepositories: getGreenSpaceList()
        activate GreenSpaceRepositories

        GreenSpaceRepositories -> List: create()
        activate List
        deactivate List

        GreenSpaceRepositories --> CTRL: greenSpaceList
        deactivate GreenSpaceRepositories

        CTRL -> MAPPER: toDto(greenSpaceList)
        activate MAPPER

        MAPPER -> ListDTO** : create()

        MAPPER -> List : greenSpace = get(i)
        activate List
        deactivate List

        MAPPER -> MAPPER : greenSpaceDto = toDTO(greenSpace)
        activate MAPPER

        MAPPER -> DTO**  : create(...)
        deactivate MAPPER

        MAPPER -> ListDTO : add(greenSpaceDto)
        activate ListDTO
        deactivate ListDTO

        MAPPER --> CTRL : greenSpaceListDto
        deactivate MAPPER

        CTRL --> UI: greenSpaceListDto

        UI --> GSM: show greenspace list and ask to select one

        GSM -> UI: selects green space

        UI -> CTRL : getDegreeUrgency()


        CTRL -> Task: getEnumDegreeUrgencyList()
        activate Task


        Task --> CTRL: enumDegreeUrgencyList
        deactivate Task

        CTRL --> UI: enumDegreeUrgencyList

        UI --> GSM: show degree of urgency list and ask to select one

        GSM -> UI: selects the urgency degree

        UI --> GSM: requests data (expected duration)

        GSM -> UI: types data

        UI --> GSM: show data and request confirmation

        GSM -> UI: confirms data

        UI -> CTRL: registerNewTask(entryDto)

        CTRL -> EntryRepository: registerNewTask(entryDto)
        activate EntryRepository

        EntryRepository -> OBJ**: create(entryDto)
        deactivate EntryRepository
        activate OBJ

        OBJ -> EntryDto: stateOfEntry = getStateOfEntry()
        activate EntryDto

        EntryDto --> OBJ: stateOfEntry

        OBJ -> EntryDto: greenSpace = getGreenSpace()

        EntryDto --> OBJ: greenSpace

        OBJ -> EntryDto: titleOfEntry = getTitleOfEntry()

        EntryDto --> OBJ: titleOfEntry

        OBJ -> EntryDto: descriptionOfEntry = getDescriptionOfEntry()

        EntryDto --> OBJ: descriptionOfEntry

        OBJ -> EntryDto: approximateExpectedDuration = getApproximateExpectedDuration()

        EntryDto --> OBJ: approximateExpectedDuration

        OBJ -> EntryDto: degreeOfUrgency = getDegreeUrgency()

        EntryDto --> OBJ: degreeOfUrgency
        deactivate EntryDto

        OBJ --> EntryRepository: true/false

        EntryRepository -> EntryRepository : verifyIfExist(entry)

        EntryRepository --> CTRL: true/false

        CTRL --> UI: true/false

        UI --> GSM : displays operation success


        deactivate UI
        deactivate GSM

@enduml