ç@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as GSM
participant ":AgendaUI" as AgendaUI
participant ":AgendaController" as AgendaController
participant ":ViewDetailsEntryUI" as UI2
participant ":ViewDetailsEntryController" as CTRL2
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "entryRepository:\nEntryRepository" as EntryRepository
participant ":EntryMapper" as MAPPER
participant "List : List<EntryDto>" as EntryDtoList
participant "entryList : List<Entry>" as EntryList
participant ":Entry" as OBJ
participant ":EntryDto" as EntryDto


activate GSM

        GSM -> AgendaUI: asks to postpone an entry in the Agenda
        activate AgendaUI

        AgendaUI -> AgendaController**: create



  AgendaUI -> AgendaController : getAgendaList()
            activate AgendaController
                        ref over AgendaController
                                Get Agenda Entry's List
                        end


            AgendaController -> AgendaUI : agendaDto
            deactivate AgendaController
        deactivate AgendaController
        AgendaUI -> GSM : show Agenda and select one Entry
                    deactivate AgendaUI
                     GSM --> AgendaUI : select one Entry
                                activate AgendaUI

                                AgendaUI --> UI2** : create
                                activate UI2
                                deactivate AgendaUI
                                UI2 --> CTRL2** : create(entryDto)

                                            UI2 --> CTRL2 : getDataNeededToModify()
                                            activate CTRL2

             CTRL2 -> RepositorySingleton : getInstance()
                                                    activate RepositorySingleton

                                                        RepositorySingleton --> CTRL2: repositories
                                                    deactivate RepositorySingleton

                                                    CTRL2 -> PLAT : getEntryRepository()
                                                    activate PLAT


                                                    PLAT -> CTRL2 : entryRepository
                                                    deactivate PLAT































deactivate GSM

@enduml