@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as GSM

participant ":ViewDetailsEntryUI" as UI2
participant ":ViewDetailsEntryController" as CTRL2
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "entryRepository:\nEntryRepository" as EntryRepository
participant "entry:Entry" as OBJ

activate GSM

ref over GSM : Get details and management options\n of a selected entry on the agenda

GSM-> UI2: Postpones the Entry Starting Date   
activate UI2

UI2 -> CTRL2: postponeEntry(newStartDate, entry)
activate CTRL2

CTRL2 -> OBJ: postponeEntry(newStartDate)
activate OBJ

OBJ -> OBJ: status.postponeState()
OBJ -> OBJ: setStartDate(newStartDate)

OBJ -> CTRL2: true

deactivate OBJ

CTRL2 -> UI2: true
deactivate CTRL2

UI2 -> GSM: Confirms the Change
deactivate UI2

@enduml
