@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox

participant ":AgendaUI" as AgendaUI
participant ":AgendaController" as AgendaController
participant ":ViewDetailsEntryUI" as UI
participant ":ViewDetailsEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "entryRepository:\nEntryRepository" as EntryRepository
participant ":EntryMapper" as MAPPER
participant "cancelEntryListDto : List<EntryDto>" as ListDTO
participant "List : List<EntryDto>" as EntryDtoList
participant "cancelEntryList : List<Entry>" as List
participant "entryList : List<Entry>" as EntryList
participant ":EntryDto" as EntryDto

        -> AgendaUI: ask to show entrys
        activate AgendaUI

        AgendaUI -> AgendaController**: create(entryDto)
        activate AgendaController


        AgendaController -> EntryRepository: getEntryByStateList()
        activate EntryRepository

        EntryRepository -> EntryDtoList**: create()

        EntryRepository --> AgendaController: entryByStateList
        deactivate EntryRepository
        deactivate AgendaController

        AgendaController -> MAPPER: toDto(entryList)
        activate MAPPER
        activate AgendaController

        MAPPER -> EntryList** : create()

        MAPPER -> EntryList : entry = get(i)
        activate EntryList
        deactivate EntryList

        MAPPER -> MAPPER : entryDto = toDTO(entry)
        activate MAPPER

        MAPPER -> EntryDto**  : create(...)
        deactivate MAPPER

        MAPPER -> ListDTO : add(entryDto)
        activate ListDTO
        deactivate ListDTO

        MAPPER --> AgendaController : entryListDto
        deactivate MAPPER

        AgendaController --> AgendaUI: entryListDto
        deactivate AgendaController




@enduml