@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ApplicationSession{
    + static getInstance()
    + getCurrentSession()
}

class UserSession{
}

class Task{
}

class CollaboratorUser {
}


class TaskRepository {
    - List <Task> : toDoList

    + getToDoListsOfCollaborator()
}

class CollaboratorRepository{
    - List<Collaborator>

    + getCollaboratorRegisteredByEmail()
}

class Collaborator {
    - String email
}


class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getEntryRepository()
    + getCollaboratorRepository()
}

class ViewTaskListAssignedCollabController {
    - TaskRepository taskRepository
    + ViewTaskListAssignedCollabController()
    + getTaskAssignedToMe()
    + getCollaboratorByEmail(email)
    - getCollaboratorFromSession()
}

class ViewTaskListAssignedCollabUI {
}

note right of ViewTaskListAssignedCollabController
    - task is achieved with task repository
end note

note bottom of TaskRepository
    - used for displaying
    the to do list
end note

Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance

ViewTaskListAssignedCollabUI .> ViewTaskListAssignedCollabController

ViewTaskListAssignedCollabController .> Repositories : repositories
Repositories "1" --> "1" TaskRepository
Repositories "1" --> "1" CollaboratorRepository

ViewTaskListAssignedCollabController ..> TaskRepository : TaskRepository


CollaboratorRepository "1" --> "*" Collaborator : collaborators

ApplicationSession --> "1" UserSession : userSession
ViewTaskListAssignedCollabController ..> ApplicationSession
ViewTaskListAssignedCollabController ..> UserSession
TaskRepository --> "*" CollaboratorUser : employs

Task --> "*" CollaboratorUser : employs




@enduml