@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Collaborator" as Collaborator
participant ":CompleteTaskUI" as UI
participant ":CompleteTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "TaskRepositories\n:TaskRepositories" as TaskRepositories
/' participant ":TaskMapper" as MAPPER
participant "taskListDto : List<TaskDto>" as ListDTO
participant "List : List<Task>" as List 
participant ":TaskDto" as DTO'/
participant "task:Task" as OBJ


activate Collaborator

Collaborator -> UI: ask to show the list of tasks
activate UI

UI -> CTRL**: create()
activate CTRL

CTRL -> RepositorySingleton: getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT: getTaskRepository()
activate PLAT

PLAT --> CTRL: taskRepository
deactivate PLAT

CTRL -> TaskRepositories: getTaskList()
activate TaskRepositories

TaskRepositories --> CTRL: taskList
deactivate TaskRepositories

CTRL --> UI: taskList
deactivate CTRL

UI --> Collaborator: shows the list of tasks

Collaborator -> UI: selects the task that wants to record the completion and submits

UI -> CTRL: completeTask(task)
activate CTRL

CTRL -> TaskRepositories: completeTask(task)
activate TaskRepositories

TaskRepositories -> OBJ: stateOfTask = setStateOfTask()
activate OBJ

OBJ --> TaskRepositories: true
deactivate OBJ

TaskRepositories --> CTRL: true/false
deactivate TaskRepositories

CTRL --> UI: true/false
deactivate CTRL

UI --> Collaborator: display operation success
deactivate UI




@enduml