@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Collaborator" as Collaborator
participant ":ViewTaskListAssignedUI" as UI
participant ":ViewTaskListAssignedController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "entryRepository\n:EntryRepository" as EntryRepository
participant "collaboratorRepository\n:CollaboratorRepository" as CollaboratorRepository



activate Collaborator

        Collaborator -> UI : asks to show the list of tasks assigned to him

        activate UI

            UI -> CTRL** : create

            UI -> CTRL : getToDoList()
            activate CTRL

             CTRL -> RepositorySingleton : getInstance()
                                        activate RepositorySingleton

                                            RepositorySingleton --> CTRL: repositories
                                        deactivate RepositorySingleton

                                        CTRL -> PLAT : getEntryRepository()
                                        activate PLAT

                                        PLAT --> CTRL : entryRepository
                                        deactivate PLAT

                                        CTRL -> EntryRepository : getToDoList()
                                        activate EntryRepository

                                        EntryRepository --> CTRL : toDoList
                                        deactivate EntryRepository

                                        CTRL --> UI : toDoList
                                        deactivate CTRL

                                        UI -> Collaborator : shows toDoList
                                        deactivate UI

                                        Collaborator -> UI : selects tasks
                                        activate UI

                                        UI -> CTRL : getTasksDone()
                                        activate CTRL

                                        CTRL -> CollaboratorRepository : getTasksDone()
                                        activate CollaboratorRepository

                                        CollaboratorRepository --> CTRL : true
                                        deactivate CollaboratorRepository
                                        CTRL --> UI : true
                                        deactivate CTRL
                                        UI --> Collaborator : displays success message
                                        deactivate UI





















@enduml