@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Collaborator" as Collaborator
participant ":CompleteTaskUI" as UI
participant ":CompleteTaskController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "TaskRepositories\n:TaskRepositories" as TaskRepositories

participant ":TaskMapper" as MAPPER
participant "taskListDto : List<TaskDto>" as ListDTO
participant "taskList : List<Task>" as List
participant ":TaskDto" as DTO


participant "task:Task" as OBJ


activate Collaborator

Collaborator -> UI: ask to show the list of tasks
activate UI

UI -> CTRL**: create()

UI -> CTRL: getTaskListDto()
activate CTRL

CTRL -> RepositorySingleton: getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT: getTaskRepository()
activate PLAT

PLAT --> CTRL: taskRepository
deactivate PLAT

CTRL -> TaskRepositories: getTaskList()
activate TaskRepositories

TaskRepositories --> CTRL: taskList
deactivate TaskRepositories



CTRL -> MAPPER : toDTO(taskList)
activate MAPPER

MAPPER -> ListDTO** : create()

loop for each object in TaskList
    MAPPER -> List : obj = get()
    activate List
    deactivate List
    MAPPER -> MAPPER: objDto = toDto(obj)
    activate MAPPER

    MAPPER -> DTO** : create(obj.getStartDate(), obj.getStatus(),\nobj.getVehicleList(), obj.getTeamAssigned(), obj.getReference())
    deactivate MAPPER
    MAPPER -> ListDTO : add(objDto)
    activate ListDTO
    deactivate ListDTO
end

deactivate List

MAPPER -> CTRL : taskListDto
deactivate MAPPER


CTRL --> UI: taskListDto
deactivate CTRL

UI --> Collaborator: shows the list of tasks

Collaborator -> UI: selects the task that wants to record the completion and submits

UI -> CTRL: completeTask(task)
activate CTRL

CTRL -> TaskRepositories: completeTask(task)
activate TaskRepositories

TaskRepositories -> OBJ: stateOfTask = setStateOfTask()
activate OBJ

OBJ --> TaskRepositories: true
deactivate OBJ

TaskRepositories --> CTRL: true/false
deactivate TaskRepositories

CTRL --> UI: true/false
deactivate CTRL

UI --> Collaborator: display operation success
deactivate UI




@enduml