@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

title Human Resources Manager Authorisation Check

actor "HR Manager" as HRManager
participant "AssignSkillsUI" as UI
participant ":AssignSkillsController" as Controller
participant "Repositories" as Repos
participant "repositories:Repositories" as reposRepos
participant "collaboratorRepository:CollaboratorRepository" as EmpRepo
participant "hrm:HRM" as HRM

activate HRManager

HRManager -> UI : Asks to assign skills to a specific employee
activate UI
UI -> Controller : checkAuthorization()
activate Controller

Controller -> Repos : getInstance()
activate Repos
Repos --> Controller : repositories
deactivate Repos

Controller -> reposRepos : getCollaboratorRepository()
activate reposRepos
reposRepos --> Controller : collaboratorRepository
deactivate reposRepos

Controller -> EmpRepo : checkHRManager(userEmail)
activate EmpRepo
EmpRepo -> HRM : isHRM(userEmail)
activate HRM
HRM --> EmpRepo : Authorization Status (true/false)
deactivate HRM
EmpRepo --> Controller : Authorization Status (true/false)
deactivate EmpRepo

alt Authorization Status is True
    Controller --> UI : Authorized
else Authorization Status is False
    Controller --> UI : Not Authorized Message
end

deactivate Controller
UI --> HRManager : Display Authorization Status
deactivate UI
@enduml
