@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class SkillRepository {
    - skillList : List<Skill>
    + SkillRepository()
    + registerSkill(skillName : String) : Optional<Skill>
    + getSkillList() : List<Skill>
    + removeSkill(skill : Skill) : void
}

class AssignSkillsUI {
    - ctrl : AssignSkillsController
    - collaborator : Collaborator
    - skillName : Skill
    + AssignSkillsUI()
    + run() : void
    + displayAndSelectSkillToAssign() : Skill
    + displayCollaboratorList() : void
    + setCollaboratorToAssign() : Collaborator
    + submitsData() : void
}

class AssignSkillsController {
    - collaboratorRepository : CollaboratorRepository
    - skillRepository : SkillRepository
    + AssignSkillsController()
    + getDataNeededToAssign() : void
    + getCollaboratorList() : List<Collaborator>
    + getCollaborator(index : int) : Collaborator
    + filterSkillsToAssign(collaborator : Collaborator) : List<Skill>
    + assignSkills(collaborator : Collaborator, skillName : Skill) : Optional<Collaborator>
}

class CollaboratorRepository {
    - collaboratorList : List<Collaborator>
    + CollaboratorRepository()
    + getCollaboratorList() : List<Collaborator>
    + createCollaborator(...) : Optional<Collaborator>
    + addCollaborator(collaborator : Collaborator) : Optional<Collaborator>
    + removeFromList(collaborator : Collaborator) : void
    + assignSkill(collaborator : Collaborator, skillName : Skill) : Optional<Collaborator>
    + getCollaboratorsNotActive() : List<Collaborator>
    + activateCollaborators(team : Team) : boolean
}

class Collaborator {
    - name : String
    - birthday : Date
    - admissionDate : Date
    - address : String
    - addressZipCode : String
    - addressCity : String
    - phoneNumber : String
    - docType : DocType.Type
    - docIDNumber : int
    - email : String
    - jobCategory : JobCategory
    - skills : List<Skill>
    - statusType : StatusType
    + Collaborator(...)
    + setName(name : String) : void
    + setBirthday(birthday : Date) : void
    + setSkills(skills : List<Skill>) : void
    + getStatus() : StatusType
    + getEmail() : String
}

class Skill {
    - name : String
}

AssignSkillsUI *-- "1" AssignSkillsController : Composition
AssignSkillsController --> "1" Repositories : uses >
AssignSkillsController --> "1" SkillRepository : uses >
AssignSkillsController --> "1" CollaboratorRepository : uses >
SkillRepository o-- "*" Skill : contains
CollaboratorRepository o-- "*" Collaborator : contains

@enduml
