@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as GSM
participant "GreenSpaceManagementUI" as UI
participant ":GreenSpaceController" as Controller


participant "UserSession" as UserSession

participant "Repositories" as Repos
participant "repositories:Repositories" as reposRepos

participant "managerRepository:ManagerRepository" as ManagerRepo
participant "greenSpaceRepository:GreenSpaceRepository" as Repo
participant "manager:Manager" as Manager
participant ":GreenSpaceMapper" as Mapper
participant "List<GreenSpace>" as GreenSpaceList
participant "List<GreenSpaceDto>" as GreenSpaceDtoList

activate GSM

GSM -> UI : Request to list managed green spaces
activate UI


UI -> Controller** : create

UI -> UserSession : getUserEmail()
activate UserSession

UserSession --> UI : userEmail
deactivate UserSession

UI -> Controller : getlistManagedGreenSpaces(userEmail)
activate Controller


Controller -> Repos : getInstance()
activate Repos

Repos --> Controller : repositories
deactivate Repos

Controller -> reposRepos : getGreenSpaceRepository()
activate reposRepos

reposRepos --> Controller : greenSpaceRepository
deactivate reposRepos

Controller -> reposRepos : getManagerRepository()
activate reposRepos

reposRepos --> Controller : managerRepository
deactivate reposRepos

Controller -> ManagerRepo : findByEmail(userEmail)
activate ManagerRepo

ManagerRepo --> Controller : manager
deactivate ManagerRepo


Controller -> Manager : getGreenSpacesManaged()
activate Manager

Manager --> Controller : GreenSpaceList
deactivate Manager

Controller -> Repo : findGreenSpacesByManager(manager)
activate Repo

Repo --> Controller : GreenSpaceList
deactivate Repo

Controller --> UI : GreenSpaceList
deactivate Controller

UI --> GSM : Shows List of GreenSpaces
deactivate UI

@enduml
