@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0

left to right direction

package "UI" #f0f0f0 {
    class GreenSpaceManagementUI {
        +requestToListManagedGreenSpaces(): void
    }
}

package "Core" #f0f0f0 {

    package "Controller" #dddddd {
        class GreenSpaceController {
            +getManagedGreenSpacesListDto(): List<GreenSpaceDto>
        }

        GreenSpaceManagementUI ..> GreenSpaceController
    }

    package "Domain" #dddddd {

        package "Mapper" #bbbbbb {
            class GreenSpaceMapper {
                +toDTO(greenSpaceList: List<GreenSpace>): List<GreenSpaceDto>
                +toDto(obj: GreenSpace): GreenSpaceDto
            }
        }

        package "DTO" #bbbbbb {
            class GreenSpaceDto {
                +name: String
                +area: Float
                +GreenSpaceDto(name: String, area: Float)
            }

            GreenSpaceMapper ..> GreenSpaceDto
        }

        package "Repository" #bbbbbb {
            class Repositories {
                - static instance: Repositories
                + getInstance(): Repositories
                + getAuthenticationRepository(): AuthenticationRepository
                + getManagerRepository(): ManagerRepository
            }

            class AuthenticationRepository {
                +getCurrentUserSession(): UserSession
            }

            class ManagerRepository {
                +findByEmail(email: String): Manager
            }

            Repositories "1" --> "1" AuthenticationRepository
            Repositories "1" --> "1" ManagerRepository
            GreenSpaceController ..> Repositories : repositories
        }

        package "Model" #bbbbbb {
            class UserSession {
                +getUser(): User
            }

            class User {
                +getEmail(): String
            }

            class Manager {
                +getGreenSpaces(): GreenSpaces
            }

            class GreenSpaces {
                +getSortedGreenSpaces(): List<GreenSpace>
            }

            class GreenSpace {
                +getName(): String
                +getArea(): Float
            }

            class Utils {
                +sortGreenSpaces(greenSpaces: List<GreenSpace>): List<GreenSpace>
            }

            GreenSpaces ..> Utils
            Manager "1" --> "*" GreenSpaces
            GreenSpaces "1" --> "*" GreenSpace
        }

        package "Adapters" #bbbbbb {
            class AuthFacade {
                +getCurrentUserSession(): UserSession
            }

            AuthenticationRepository "1" --> "1" AuthFacade
        }
    }
}
@enduml
