@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0

left to right direction

package "UI" #f0f0f0 {
    class ManageGreenSpacesUI {
    }
}

package "Core" #f0f0f0 {

    package "Controller" #dddddd {
        class RegisterGreenSpaceController {
            +getGreenSpacesByEmail(): List<GreenSpaceDto>
            +getCollaboratorFromSession(): String
            +getSortAlgorithm(): SortingList
        }
    }

    package "Session" #dddddd {
        class ApplicationSession {
            -instance: ApplicationSession
            +getCurrentSession(): UserSession
            +getAlgorithmService(): SortingList
        }

        class UserSession {
            +getUserEmail(): String
        }
    }

    package "SortingAlgorithmsServ" #dddddd {
        interface SortingList {
            + sortingList(list: List<GreenSpaceDto>): List<GreenSpaceDto>
        }

        class SortingAlgorithm1 implements SortingList {
            + sortingList(list: List<GreenSpaceDto>): List<GreenSpaceDto>

        }

        class SortingAlgorithm2 implements SortingList {
            + sortingList(list: List<GreenSpaceDto>): List<GreenSpaceDto>
        }


    }

    package "Mapper" #dddddd {
        class GreenSpaceMapper {
            +greenSpaceListToGreenSpaceDtoList(greenSpaceList: List<GreenSpace>): List<GreenSpaceDto>
            +toDto(greenSpace: GreenSpace): GreenSpaceDto
        }
    }

    package "DTO" #dddddd {
        class GreenSpaceDto {
            +name: String
            +location: String
            +size: float
            +createdBy: String
        }
    }
    package "Domain" #dddddd {

        package "Repository" #bbbbbb {
            class Repositories {
                - organizationRepository: Organization
                - static instance : Repositories
                + getInstance() : Repositories
                + getOrganizationRepository() : Organization
                - Repositories()
            }

            class Organization {
                +getGreenSpaceListByManagerEmail(email: String): List<GreenSpace>
            }
        }

        package "Model" #bbbbbb {
            class GreenSpace {
                +name: String
                +location: String
                +size: float
                +createdBy: String
            }
        }

    }
}

ManageGreenSpacesUI ..> RegisterGreenSpaceController
RegisterGreenSpaceController ..> Repositories : repositories
RegisterGreenSpaceController ..> Organization : organization
RegisterGreenSpaceController ..> GreenSpaceMapper
RegisterGreenSpaceController ..> SortingList : sortAlgorithm
RegisterGreenSpaceController ..> UserSession
RegisterGreenSpaceController ..> ApplicationSession
RegisterGreenSpaceController ..> GreenSpaceDto
RegisterGreenSpaceController ..> SortingAlgorithm1
RegisterGreenSpaceController ..> SortingAlgorithm2
SortingAlgorithm1 ..> GreenSpaceDto
SortingAlgorithm2 ..> GreenSpaceDto
SortingList ..> GreenSpaceDto
ApplicationSession ..> UserSession
ApplicationSession ..> SortingList
GreenSpaceMapper ..> GreenSpaceDto
GreenSpaceMapper ..> GreenSpace
Organization "1" --> "*" GreenSpace
Repositories "1" --> "1" Organization
Repositories --> Repositories : instance

@enduml
