@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0

left to right direction

package "UI" #f0f0f0 {
    class ManageGreenSpacesUI {
    }
}

package "Core" #f0f0f0 {
    
    package "Controller" #dddddd {
        class RegisterGreenSpaceController {
            +getGreenSpacesByEmail(): List<GreenSpaceDto>
            +getCollaboratorFromSession(): String
            +getSortAlgorithm(): SortingList
        }
    }

    package "Session" #dddddd {
        class ApplicationSession {
            -instance: ApplicationSession
            +getInstance(): ApplicationSession
            +getCurrentSession(): UserSession
            +getAlgorithmService(): SortingList
        }

        class UserSession {
            +getUserEmail(): String
        }
    }

    package "Domain" #dddddd {
        
        package "Mapper" #dddddd {
            class GreenSpaceMapper {
                +greenSpaceListToGreenSpaceDtoList(greenSpaceList: List<GreenSpace>): List<GreenSpaceDto>
                +toDto(greenSpace: GreenSpace): GreenSpaceDto
            }
        }

        package "DTO" #dddddd {
            class GreenSpaceDto {
                +name: String
                +location: String
                +size: float
                +createdBy: String
            }
        }

        package "Repository" #bbbbbb {
            class Repositories {
                -organization: Organization
                -static instance: Repositories
                +getInstance(): Repositories
                +getOrganization(): Organization
            }

            class Organization {
                +getGreenSpaceListByManagerEmail(email: String): List<GreenSpace>
            }
        }

        package "Model" #bbbbbb {
            class GreenSpace {
                +name: String
                +location: String
                +size: float
                +createdBy: String
            }
        }

        package "Service" #bbbbbb {
            class SortingList {
                +sortingList(greenSpaceList: List<GreenSpaceDto>): List<GreenSpaceDto>
            }
        }
    }
}

ManageGreenSpacesUI ..> RegisterGreenSpaceController
RegisterGreenSpaceController ..> Repositories : repositories
RegisterGreenSpaceController ..> Organization : organization
RegisterGreenSpaceController ..> GreenSpaceMapper
RegisterGreenSpaceController ..> SortingList : sortAlgorithm
RegisterGreenSpaceController ..> UserSession
RegisterGreenSpaceController ..> ApplicationSession
RegisterGreenSpaceController ..> GreenSpaceDto
ApplicationSession ..> UserSession
ApplicationSession ..> SortingList
GreenSpaceMapper ..> GreenSpaceDto
GreenSpaceMapper ..> GreenSpace
Organization "1" --> "*" GreenSpace
Repositories "1" --> "1" Organization
@enduml
