@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "GSM" as GreenSpaceManager

participant ":ManageGreenSpacesUI" as UI
participant ":RegisterGreenSpaceController" as Controller
participant ":ApplicationSession" as Session
participant ":UserSession" as UserSession


participant "Repositories" as Repos
participant "repositories:Repositories" as reposRepos

participant "organization:Organization" as Org
participant "greenSpaceList:List<GreenSpace>" as GreenSpaceList
participant "greenSpace:GreenSpace" as GreenSpace
participant ":GreenSpaceMapper" as Mapper
participant "greenSpaceListDto:List<GreenSpaceDto>" as GreenSpaceListDto
participant "greenSpaceDto:GreenSpaceDto" as GreenSpaceDto
participant "sortAlgorithm:SortingList" as SortAlgorithm

activate GreenSpaceManager

GreenSpaceManager -> UI : Request to list all green spaces managed by the GSM
activate UI

UI -> Controller** : create


UI -> Controller: getGreenSpacesByEmail()
activate Controller

Controller -> Repos: getInstance()
activate Repos

Repos --> Controller: repositories
deactivate Repos

Controller -> reposRepos: getOrganization()
activate reposRepos

reposRepos --> Controller: organization
deactivate reposRepos

Controller -> Controller : getCollaboratorFromSession()
activate Controller

Controller -> Session: getCurrentSession()
activate Session

Session -> Controller: userSession
deactivate Session

Controller -> UserSession: getUserEmail()
activate UserSession

UserSession -> Controller : userEmail
deactivate UserSession
deactivate Controller

Controller -> Org: getGreenSpaceListByManagerEmail(UserEmail)
activate Org

Org -> GreenSpaceList** : create()

loop for each greenSpace in greenSpaces
    Org -> GreenSpace : GSMEmail = createdBy()
    activate GreenSpace
    deactivate GreenSpace    
    alt greenSpace was created by the GSM who is currently logged in\n, i.e, whose email is stored in email attribute
        Org -> GreenSpaceList : add(greenSpace)
        activate GreenSpaceList
        deactivate GreenSpaceList
    end
end

Org -> Controller: GreenSpaceList
deactivate Org

Controller -> Mapper: greenSpaceListToGreenSpaceDto(GreenSpaceList)
activate Mapper

Mapper -> GreenSpaceListDto** : create()

loop for each greenSpace in GreenSpaceList
    Mapper -> GreenSpaceList : greenSpace = get()
    activate GreenSpaceList
    deactivate GreenSpaceList
    Mapper -> Mapper: greenSpaceDto = toDto(greenSpace)
    activate Mapper

    Mapper -> GreenSpaceDto** : create(greenSpace All Getters)
    deactivate Mapper
    Mapper -> GreenSpaceListDto : add(greenSpaceDto)
    activate GreenSpaceListDto
    deactivate GreenSpaceListDto
end

Mapper -> Controller: greenSpaceListDto
deactivate Mapper


Controller -> Controller : getSortAlgorithm()
activate Controller

Controller -> Session : getAlgorithmService()
activate Session
Session -> Controller : sortAlgorithm

deactivate Session
deactivate Controller


Controller -> SortAlgorithm: sortingList(greenSpaceListDto)
activate SortAlgorithm

SortAlgorithm -> Controller: sortedList
deactivate SortAlgorithm

Controller -> UI: sortedList
deactivate Controller

UI -> GreenSpaceManager: Shows Sorted List of the Managed Green Spaces
deactivate UI

@enduml
