@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "GSM" as Manager
participant ":System" as System

activate Manager 

    Manager -> System : cancel an entry in the Agenda
    activate System

        System --> Manager : requests confirmation
    deactivate System



@enduml