@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "GSM" as Manager
participant ":System" as System

activate Manager 

    Manager -> System : ask to show entrys
    activate System

    System --> Manager : shows detais and wait
    deactivate System

    Manager -> System : ask and select an entry to cancel
    activate System

    System --> Manager : request confirmation to cancel the entry
    deactivate System

    Manager -> System : confirms data
    activate System

    System --> Manager : display operation success
    deactivate System


@enduml