@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "GSM" as Manager
participant ":System" as System

activate Manager 

    Manager -> System : ask to cancel an entry
    activate System

    System --> Manager : shows the entrys to cancel
    deactivate System

    Manager -> System : select the entry that wants to cancel
    activate System

    System --> Manager : request confirmation to cancel the entry
    deactivate System

    Manager -> System : confirms data
    activate System

    System --> Manager : display operation success
    deactivate System


@enduml