@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Register Vehicle Check-Up Success Scenario

autonumber

actor "FM" as FleetManager
participant ":System" as System

activate FleetManager

    FleetManager -> System : requests to register a vehicle check-up
    activate System

        System --> FleetManager : requests Vehicle ID, Date of Check-Up, Current Kilometers
    deactivate System

    FleetManager -> System : provides Vehicle ID, Date of Check-Up, Current Kilometers
    activate System

        System -> System : validate Vehicle ID format
        System -> System : validate Date of Check-Up
        System -> System : validate Current Kilometers

        System --> FleetManager : confirms registration success
    deactivate System

@enduml
