@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":JobController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "collaboratorRepository\n:CollaboratorRepository" as CollaboratorRepository

autonumber 12
-> CTRL : getJobCategoryByDescription(jobCategoryDescription)

autonumber 12.1

activate CTRL
    group Verify DocIDNumber
                                    CTRL -> RepositorySingleton : getInstance()
                                    activate RepositorySingleton

                                        RepositorySingleton --> CTRL: repositories
                                    deactivate RepositorySingleton

                                    CTRL -> PLAT : getCollaboratorRepository()
                                    activate PLAT

                                        PLAT --> CTRL: CollaboratorRepository
                                    deactivate PLAT

                                    CTRL -> CollaboratorRepository : verifyDocType(docIDNumber)
                                    activate CollaboratorRepository

                                        CollaboratorRepository --> CTRL : true/false
                                    deactivate CollaboratorRepository
    end group

    autonumber 13
    <-- CTRL : true

deactivate CTRL


@enduml