@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUserEmail()
}

class Employee {
    - name
    - email
    - position
    - phone
}

class Collaborator {
    - String reference
    - String description
    - String informalDescription
    - String technicalDescription
    - Integer duration
    - Double cost

    + Collaborator(reference, description,\ninformalDescription, technicalDescription,\nduration, cost, createdBy, jobCategory)
}

class JobCategory {
    - String description

    + JobCategory(description)
}

class Organization {
    - String name
    - String vatNumber
    - String website
    - String phone
    - String email

    - addCollaborator(collaborator)
    - validateCollaborator(collaborator)
    + anyEmployeeHasEmail(email)
    + Organization(name, vatNumber, webSite, phone, email, postalAddress, manager)
    + registerCollaborator(reference, description, informalDescription,\ntechnicalDescription, duration, cost, jobCategoryDescription)
    - getEmployeeByEmail(email)

'  +saveCollaborator(collaborator)
}

class JobCategoryRepository {
    + getJobCategoryByDescription(description)
}

class OrganizationRepository {
    + getOrganizationByEmployeeEmail(email)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getJobCategoryRepository()
    + getOrganizationRepository()
}

class RegisterCollaboratorController {
    + RegisterCollaboratorController(organizationRepository, jobCategoryRepository)
    + getJobCategories()
    + registerCollaborator(userEmail, reference, description,\ninformalDescription, technicalDescription,\nduration, cost, categoryDescription)
    - getEmployeeFromSession()
}

note right of RegisterCollaboratorController
    - userEmail is obtained
    from the user session
    - categoryDescription
    is retrieved from selected data
end note

note bottom of JobCategoryRepository
    - used for displaying
    the job category list
end note

class RegisterCollaboratorUI {
}

Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance

RegisterCollaboratorUI .> RegisterCollaboratorController

RegisterCollaboratorController .> Repositories : repositories

Repositories -> "1" JobCategoryRepository

RegisterCollaboratorController ..> JobCategory
RegisterCollaboratorController ..> OrganizationRepository : organizationRepository
RegisterCollaboratorController ..> JobCategoryRepository : JobCategoryRepository

Repositories --> "1" OrganizationRepository

OrganizationRepository --> "*" Organization
ApplicationSession --> "1" UserSession : userSession

RegisterCollaboratorController ..> "1" Organization : organization
RegisterCollaboratorController ..> ApplicationSession
RegisterCollaboratorController ..> UserSession
Collaborator "*" --> "1" JobCategory : jobCategory
JobCategoryRepository "1" --> "*" JobCategory : jobCategory
Organization "1" --> "*" Collaborator : collaborators
Collaborator --> Employee : createdBy

Organization --> "*" Employee : employs

@enduml