@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "HRM" as HRM
participant ":RegisterCollaboratorUI" as UI
participant ":RegisterCollaboratorController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "jobCategoryRepository:\nJobCategoryRepository" as JobCategoryRepository
participant "collaboratorRepository\n:CollaboratorRepository" as CollaboratorRepository
participant "collaborator\n:Collaborator" as Collaborator

activate HRM

        HRM -> UI : asks to register a Collaborator

        activate UI

'            UI --> HRM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create

            UI -> CTRL : getJobCategories()
            activate CTRL

                ref over CTRL
                            Get JobCategoryList

                        end ref

                CTRL --> UI : jobCategoryList
            deactivate CTRL

            UI --> HRM : shows job category list\n and asks to select one
        deactivate UI

    HRM -> UI : selects a job category
    activate UI






    UI -> CTRL : getDocTypeList()
                activate CTRL

                  ref over CTRL
                              Get DocTypeList with Class Enum DocType
                          end ref
    CTRL --> UI : docTypeList
    deactivate CTRL



    UI --> HRM : shows docTypeList\n and asks to select one
    deactivate UI

    HRM -> UI : selects a docType
    activate UI


    UI --> HRM : requests data
    deactivate UI








    HRM -> UI : types requested data (name, date of birthday, admission data,\n address street, zipcode, address city, email,\n phone number, number of ID card)
    activate UI

        UI --> HRM : shows selected category and requested data
    deactivate UI

    HRM -> UI : submits data
    activate UI

        UI -> CTRL : registerCollaborator(name, date of birthday, admission data,\n address street, zipcode, address city, email,\n phone number, docType, docIDNumber, jobCategory)
        activate CTRL


                            ref over CTRL
                                        Verify Doc Type with DocType Class

                                    end ref



            CTRL -> CollaboratorRepository: registerCollaborator(name, date of birthday,\n admission data, address street, zipcode, address city, email, phone number,\n docType, docIDNumber, jobCategory)
            activate CollaboratorRepository

                ref over CollaboratorRepository
                            Create and Save Collaborator

                        end ref

                CollaboratorRepository --> CTRL : true / collaboratorList

            deactivate CollaboratorRepository

            CTRL --> UI: true / collaboratorList
            deactivate CTRL
            UI --> HRM : displays operation success / show collaboratorList
    deactivate UI

deactivate HRM

@enduml