@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

participant ":RegisterCollaboratorController" as CTRL
participant ":DocType" as DocType

autonumber 12
-> CTRL : verifyDocType()

autonumber 12.1

activate CTRL
    group Verify DocIDNumber
                   CTRL -> DocType : verifyDocTypeNumber(docIDNumber)
                   activate DocType

                   DocType --> CTRL : true/false
                   deactivate DocType
    end group

    autonumber 13
    <-- CTRL : true

deactivate CTRL


@enduml