@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "GSM" as Manager
participant ":System" as System

activate Manager 

    Manager -> System : asks to assign Vehicles to an Entry
    activate System

        System --> Manager : show Agenda Entry list and ask to select one Entry
    deactivate System

    Manager -> System : selects an Entry
    activate System

loop
    System --> Manager  : shows Entry information and Vehicle list \nand ask to select vehicle
        deactivate System

        Manager  -> System : selects a vehicle
        activate System

     System --> Manager : ask if want to add more
        deactivate System

        Manager --> System : introduce yes and select another vehicle to assign
        activate System
end

        System --> Manager  : shows all data and requests confirmation
    deactivate System

    Manager  -> System : confirms data
    activate System

        System --> Manager : displays operation success / show Entry in Agenda
    deactivate System

@enduml