@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative One

autonumber

actor "GSM" as Manager
participant ":System" as System

activate Manager 

    Manager -> System : asks to add a new Entry on Agenda
    activate System

    System --> Manager : show the To Do List and ask to \n select one Entry
    deactivate System

    Manager -> System : select a Entry
    activate System

        System --> Manager : requests data (i.e. Date)
    deactivate System

   Manager  -> System : types requested data
    activate System

    alt System Verification
    System --> System  : verify data
    end

        System --> Manager  : shows all data and requests confirmation
    deactivate System

    Manager  -> System : confirms data
    activate System

        System --> Manager : displays operation success / show agenda
    deactivate System

@enduml