@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Alternative Two

autonumber

actor "GSM" as Manager
participant ":System" as System

activate Manager

    Manager -> System : asks to add a new entry on Agenda
    activate System

        System --> Manager : shows task list and asks to select one
    deactivate System

    Manager -> System : selects a task
    activate System

        System  --> Manager : requests data (timePeriod)

        System --> Manager :shows all data and requests confirmation
    deactivate System

    Manager -> System : confirms data
    activate System

        System --> Manager : displays operation success / show list of existing collaborators
    deactivate System
@enduml