@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

'class Platform {
'  -description
'}
class UserSession{

}

class Collaborator {
    name
    email
    password
}

class Entry{
    startDate
    status
}

class Task{
    greenSpaceAssigned
    degreeUrgency
    timeExpected
}


class Equipment{
}

class Vehicle{
}



Collaborator "1" -- "0..*" Task: have >


Entry "1" - "1" Task : extends

Entry "1" -- "0..1" Team : have >

Entry "1" -- "0..*" Vehicle : have >

Entry "1" -- "0..*" Equipment : have >

Team "0..1" -- "1" Collaborator : have <

Team "1" -- "0..*" Skills : have >

UserSession "1" -- "0..*" Collaborator : have <

@enduml