ç@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as GSM
participant ":AgendaUI" as AgendaUI
participant ":AgendaController" as AgendaController
participant ":ViewDetailsEntryUI" as UI
participant ":ViewDetailsEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "entryRepository:\nEntryRepository" as EntryRepository
participant ":Entry" as OBJ
participant ":EntryDto" as EntryDto
participant ":EntryMapper" as MAPPER
participant "cancelEntryListDto : List<EntryDto>" as ListDTO
participant "cancelEntryList : List<Entry>" as List
participant "Task:\nTask" as Task


activate GSM

        GSM -> AgendaUI: selects entry
        activate AgendaUI

        AgendaUI -> AgendaController**: create(entryDto)
        deactivate AgendaUI

        AgendaUI -> GSM: shows details and wait
        activate AgendaUI

        deactivate AgendaUI

        GSM -> UI : ask to cancel an entry
        activate UI

        UI -> CTRL**: cancelEntry(entryDto)
        activate CTRL

        CTRL -> RepositorySingleton: getInstance()
        activate RepositorySingleton

        RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT: getEntryRepository()
        activate PLAT

        PLAT --> CTRL: entryRepository
        deactivate PLAT

        CTRL -> RepositorySingleton: changeEntryStatus(entryDto)
        activate RepositorySingleton

        RepositorySingleton -> MAPPER: toModel(entryDto)
        deactivate RepositorySingleton











        CTRL --> UI: entryListDto

        UI --> GSM: shows the entrys to cancel

        GSM -> UI: select the entry that wants to cancel

        UI --> GSM: request confirmation to cancel the entry

        GSM -> UI: confirms data

        UI --> GSM : displays operation success
        deactivate UI

deactivate GSM

@enduml