ç@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
participant ":ViewDetailsEntryUI" as UI
participant ":ViewDetailsEntryController" as CTRL
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "entryRepository:\nEntryRepository" as EntryRepository
participant ":EntryMapper" as MAPPER
participant "cancelEntryListDto : List<EntryDto>" as ListDTO
participant "List : List<EntryDto>" as EntryDtoList
participant "cancelEntryList : List<Entry>" as List
participant "entryList : List<Entry>" as EntryList
participant ":Entry" as OBJ
participant ":EntryDto" as EntryDto

 -> UI : ask and select an entry to cancel
        activate UI

        UI -> CTRL**: cancel()
        activate CTRL

        CTRL -> RepositorySingleton: getInstance()
        activate RepositorySingleton

        RepositorySingleton --> CTRL: repositories
        deactivate RepositorySingleton

        CTRL -> PLAT: getEntryRepository()
        activate PLAT

        PLAT --> CTRL: entryRepository
        deactivate PLAT

        <--UI: request confirmation to cancel the entry

        -> UI: confirms data

        UI -> CTRL: cancelEntry(entryDto)

        CTRL -> EntryRepository: cancelEntry(entryDto)
        activate EntryRepository

        EntryRepository -> OBJ**: cancelEntry(entryDto)
        deactivate EntryRepository
        activate OBJ


        OBJ -> EntryDto: stateOfEntry = setStateOfEntry()
        activate EntryDto

        EntryDto --> OBJ: stateOfEntry
        deactivate EntryDto

        OBJ --> EntryRepository: true/false
        deactivate OBJ
        activate EntryRepository


        EntryRepository --> CTRL: true/false
        deactivate EntryRepository

        CTRL --> UI: true/false


deactivate GSM

@enduml