@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUserEmail()
}

class Employee {
    - name
    - email
    - position
    - phone
}

class Vehicle {
    - String brand
    - String model
    - Integer plate
    - String type
    - Integer tare
    - String grossWeight
    - Integer currenteKM
    - String registerDate
    - String acquisitionDate
    - Integer checkupFrequency

    + Vehicle(brand, model, plate, type, tare, grossWeight, currenteKM, registerDate, acquisitionDate, checkupFrequency)
}

class Organization {
    - String name
    - String vatNumber
    - String website
    - String phone
    - String email


    + Organization(name, vatNumber, webSite, phone, email, postalAddress, manager)
    + createVehicle(brand, model, plate,type, tare, grossWeight, currenteKM, registerDate, acquisitionDate, checkupFrequency)
    - getEmployeeByEmail(email)

}

class VehicleTypeRepository {
    + getVehicleTypeByDescription(description)
}

class OrganizationRepository {
    + getOrganizationByEmployeeEmail(email)
}

class Repositories {
    - Repositories()
    + getInstance() : Repositories
    + getVehicleTypeRepository()
    + getOrganizationRepository()
}

class RegisterVehicleController {
    + RegisterVehicleController(organizationRepository, vehicleTypeRepository)
    + getTaskCategories()
    + createTask(userEmail, reference, description,\ninformalDescription, technicalDescription,\nduration, cost, categoryDescription)
    - getTaskCategoryByDescription(taskCategoryDescription)
    - getEmployeeFromSession()
}

note right of RegisterVehicleController
    - userEmail is obtained
    from the user session
    - categoryDescription
    is retrieved from selected data
end note

note bottom of VehicleTypeRepository
    - used for displaying
    the type list
end note

class RegisterVehicleUI {
}

Repositories -> Repositories : instance
ApplicationSession -> ApplicationSession : instance

RegisterVehicleUI .> RegisterVehicleController

RegisterVehicleController .> Repositories : repositories

Repositories -> "1" VehicleTypeRepository

RegisterVehicleController ..> TaskCategory
RegisterVehicleController ..> OrganizationRepository : organizationRepository
RegisterVehicleController ..> VehicleTypeRepository : VehicleTypeRepository

Repositories --> "1" OrganizationRepository

OrganizationRepository --> "*" Organization
ApplicationSession --> "1" UserSession : userSession

RegisterVehicleController ..> "1" Organization : organization
RegisterVehicleController ..> ApplicationSession
RegisterVehicleController ..> UserSession
Vehicle "*" --> "1" TaskCategory : taskCategory
VehicleTypeRepository "1" --> "*" TaskCategory : taskCategory
Organization "1" --> "*" Task : tasks
Vehicle --> Employee : createdBy

Organization --> "*" Employee : employs

@enduml