@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
'skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class ApplicationSession
{
    + static getInstance()
    + getCurrentSession()
}

class UserSession
{
    + getUserEmail()
}

class VFM {
    - name
    - email
    - position
    - phone
}

class Vehicle {
    - String brand
    - String model
    - Integer plate
    - String type
    - Integer tare
    - String grossWeight
    - Integer currenteKM
    - String registerDate
    - String acquisitionDate
    - Integer checkupFrequency

    + Vehicle(brand, model, plate, type, tare, grossWeight, currenteKM, registerDate, acquisitionDate, checkupFrequency)
}



class VehicleRepository {
}


class Repositories {
    + getInstance() : Repositories
    + getVehicleRepository() : VehicleRepository
}

class RegisterVehicleController {
    - VehicleRepository vehicleRepository
    + RegisterVehicleController(vehicleRepository)
    + registerVehicle(brand, model, type, tare, gross weight, current km, \nregister date, acquisition date, maintenance/check-up frequency (in kms)))
    + getVehicleList()
    + removeVehicleFromList(selectedVehicle)
    + updateKm(selectedVehicle, km)
}

note right of RegisterVehicleController
    - userEmail is obtained
    from the user session
    - categoryDescription
    is retrieved from selected data
end note

note bottom of VehicleRepository
    - used for displaying
    the vehicle list
end note

Repositories "1" --> "1" VehicleRepository
Repositories "1" -> "1" Repositories

ApplicationSession --> ApplicationSession
ApplicationSession --> "1" UserSession : userSession

RegisterVehicleUI "1" --> "1" RegisterVehicleController

RegisterVehicleController .> Repositories
RegisterVehicleController ..> ApplicationSession
RegisterVehicleController ..> UserSession
RegisterVehicleController "1" --> "1" VehicleRepository

Vehicle --> VFM : createdBy

VehicleRepository "1" --> "*" Vehicle : vehicles

@enduml