@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "VFM" as VFM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as Repositories
participant "repositories:Repositories" as Repo
participant "vehicleRepository\n:VehicleRepository" as VehicleRepository
participant "vehicle\n:Vehicle" as Vehicle

activate VFM

    VFM -> UI : asks to register a Vehicle
    activate UI

    UI -> CTRL** : create
    activate CTRL

    CTRL -> Repositories : getInstance()
    activate Repositories

    Repositories --> CTRL: repositories
    deactivate Repositories

    CTRL -> Repo : getVehicleRepository()
    activate Repo

    Repo -> CTRL : vehicleRepository
        deactivate Repo

    deactivate CTRL

    UI --> VFM : requests data brand, model, type, tare, gross weight, current km, register date, acquisition date, maintenance/check-up frequency (in kms))

    VFM -> UI : types requests data(brand, model, type, tare, gross weight, current km, register date, acquisition date, maintenance/check-up frequency (in kms))

    UI --> VFM : shows all data and requests confirmation

    VFM -> UI : confirms data

    UI -> CTRL : registerVehicle(brand, model, type, tare, gross weight, current km, \nregister date, acquisition date, maintenance/check-up frequency (in kms))
    activate CTRL

    CTRL -> VehicleRepository: registerVehicle(brand, model, type, tare, gross weight, current km, \nregister date, acquisition date, maintenance/check-up frequency (in kms))
    activate VehicleRepository

    VehicleRepository -> Vehicle**: createVehicle()
    VehicleRepository -> VehicleRepository: addVehicle(vehicle)
    VehicleRepository --> Repositories : true / vehicle


    Repositories --> CTRL : true / vehicle
    deactivate VehicleRepository

    CTRL --> UI: true / vehicle
    deactivate CTRL

    UI -> VFM : displays operation success
    deactivate UI

deactivate VFM

@enduml