@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "VFM" as VFM
participant ":RegisterVehicleUI" as UI
participant ":RegisterVehicleController" as CTRL
participant ":Repositories" as Repositories
participant "vehicleRepository\n:VehicleRepository" as VehicleRepository
participant "vehicle\n:Vehicle" as Vehicle

activate VFM

        VFM -> UI : asks to register a Vehicle
        activate UI

    UI --> VFM : requests data brand, model, type, tare, gross weight, current km, register date, acquisition date, maintenance/check-up frequency (in kms))

    VFM -> UI : types requests data(brand, model, type, tare, gross weight, current km, register date, acquisition date, maintenance/check-up frequency (in kms))

    UI --> VFM : shows all data and requests confirmation

    VFM -> UI : confirms data

        UI -> CTRL : registerVehicle(brand, model, type, tare, gross weight, current km, \nregister date, acquisition date, maintenance/check-up frequency (in kms))
        activate CTRL


                            CTRL -> Repositories : getInstance()
                            activate Repositories


                            CTRL -> Repositories : getVehicleRepository()
                            activate VehicleRepository

                            Repositories -> VehicleRepository : getVehicleRepository()



                            CTRL -> Repositories: registerVehicle(brand, model, type, tare, gross weight, current km, \nregister date, acquisition date, maintenance/check-up frequency (in kms))

                            Repositories -> VehicleRepository : registerVehicle(brand, model, type, tare, gross weight, current km, \nregister date, acquisition date, maintenance/check-up frequency (in kms))
                            VehicleRepository -> Vehicle: createVehicle()
                            Vehicle -> VehicleRepository: addVehicle(vehicle)
                            VehicleRepository --> Repositories : true / vehicle

                            VehicleRepository --> Repositories: vehicleRepository
                            deactivate VehicleRepository

                            Repositories --> CTRL : true / vehicle

                            Repositories --> CTRL: repositories


                    deactivate VehicleRepository

                    CTRL --> UI: true / vehicle
                    deactivate CTRL
    UI -> VFM : displays operation success
    deactivate UI

deactivate VFM

@enduml