@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title UI Sequence Diagram (SSD) for Registering Vehicle Maintenance

autonumber

actor "VFM" as FleetManager


participant ":RegisterCheckUpUI" as UI
participant ":RegisterCheckUpController" as Controller

participant "Repositories" as Repos
participant "repositories:Repositories" as Repo
participant "vehicleRepository:VehicleRepository" as VehicleRepo


participant ":VehicleMapper" as VehicleMapper
/' participant ":CheckupMapper" as CheckupMapper '/

participant "listVehicle:list<Vehicle>" as listVehicle
/' participant "listCheckup:list<Checkup>" as listCheckup
 '/
participant "VehicleNamesDto:list<String>" as VehicleNamesDto
participant "objDto:VehicleDto" as VehicleDto

/'participant "availableCheckupsNamesDto:list<String>" as availableCheckupsNamesDto
participant "objDto:CheckupDto" as CheckupDto
 '/

participant "vehicle:Vehicle" as Vehicle
participant "checkup:Checkup" as Checkup
 '/
activate FleetManager


FleetManager -> UI : Asks to register a maintenance
activate UI

UI -> Controller** : create

UI -> Controller : getDataNeededToRegisterCheckUp()
activate Controller

Controller -> Repos : getInstance()
activate Repos

Repos --> Controller : repositories
deactivate Repos        

Controller -> Repo : getVehicleRepository()
activate Repo
Repo --> Controller : vehicleRepository
deactivate Repo

Controller -> VehicleRepo : getVehicleList()
activate VehicleRepo

VehicleRepo --> Controller : vehicleList
deactivate VehicleRepo









Controller -> VehicleMapper : toDTO(VehicleList)
activate VehicleMapper

VehicleMapper -> VehicleNamesDto** : create()

loop for each object in VehicleList
    VehicleMapper -> listVehicle : obj = get()
    activate listVehicle
    deactivate listVehicle
    VehicleMapper -> VehicleMapper: objDto = toDto(obj)
    activate VehicleMapper

    VehicleMapper -> VehicleDto** : create(...)
    deactivate VehicleMapper
    VehicleMapper -> VehicleNamesDto : add(objDto.getPlate())
    activate VehicleNamesDto
    deactivate VehicleNamesDto
end

deactivate listVehicle

VehicleMapper -> Controller : VehiclesPlatesDto
deactivate VehicleMapper


Controller --> UI : vehiclePlatesDto
deactivate Controller

UI --> FleetManager : Show Plates, Request Date of Check Up and Current Kilometers and Frequency Option
deactivate UI

FleetManager -> UI : Selects a Plate, Provides Check Up Info, Changes Check Up Frequency and Submits
activate UI

UI -> UI : verifyCheckUpDateFormat(date)
UI -> UI : validateCheckUpDate(date)

UI -> UI : verifyKilometersFormat(currentKms)

UI -> Controller : validateKilometers(currentKms, selectedPlate)
activate Controller


Controller -> VehicleRepo: getLastKmForVehicle(plate)
activate VehicleRepo

VehicleRepo -> Controller: currentKm
deactivate VehicleRepo

Controller -> UI : true
deactivate Controller







UI -> Controller : addCheckUp(objDto) /' selectedPlate, date, currentKms, maintenanceKm '/
activate Controller

Controller -> VehicleRepo : addCheckUp(objDto)
activate VehicleRepo

VehicleRepo -> VehicleMapper : toModel(objDto)
activate VehicleMapper

VehicleMapper -> VehicleDto : selectedPlate = getPlate()
activate VehicleDto
deactivate VehicleDto

VehicleMapper -> VehicleDto : dateOfCheck = getDate()
activate VehicleDto
deactivate VehicleDto

VehicleMapper -> VehicleDto : currentKms = getCurrentKms()
activate VehicleDto
deactivate VehicleDto

VehicleMapper -> VehicleDto : maintenanceKm = getMaintenanceKms()
activate VehicleDto
deactivate VehicleDto




VehicleMapper -> VehicleRepo : findVehicleByPlate(plate)
activate VehicleRepo

VehicleRepo -> VehicleMapper : vehicle
deactivate VehicleRepo

VehicleMapper -> Vehicle : addCheckUp(currentKms, dateOfCheck, maintenanceKms)
activate Vehicle

Vehicle -> Checkup** : create(currentKms, dateOfCheck)
activate Checkup

Checkup -> Vehicle : Created and Added to the Check Up List of the Vehicle which was under maintenance 
deactivate Checkup

Vehicle --> VehicleMapper : true
deactivate Vehicle

VehicleMapper --> VehicleRepo : true
deactivate VehicleMapper

VehicleRepo --> Controller : true
deactivate VehicleRepo

Controller -> UI : Success
deactivate Controller

UI --> FleetManager : Confirms registration success
deactivate UI

@enduml
