@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "HR Manager" as HRManager
participant "AssignSkillsUI" as UI
participant ":AssignSkillsController" as Controller

participant "Repositories" as Repos
participant "repositories:Repositories" as reposRepos
participant "collaboratorRepository:CollaboratorRepository" as EmpRepo
participant "skillRepository:SkillRepository" as SkillRepo
participant ":CollaboratorMapper" as EmpMapper
participant ":SkillMapper" as SkillMapper

participant "collaboratorList:list<Collaborator>" as listEmp
participant "availableSkillList:list<Skill>" as listSkill

participant "collaboratorListDto:list<CollaboratorDto>" as CollaboratorListDto
participant "objDto:CollaboratorDto" as CollaboratorDto

participant "skillListDto:list<SkillDto>" as SkillListDto
participant "objDto:SkillDto" as SkillDto


participant "collaborator:Collaborator" as Collaborator
participant "skills:Skills" as Skills

activate HRManager

HRManager -> UI : Asks to assign skills to a specific collaborator
activate UI

UI -> Controller** : create

UI -> Controller : getCollaboratorListDto()
activate Controller

Controller -> Repos : getInstance()
activate Repos

Repos --> Controller : repositories
deactivate Repos

Controller -> reposRepos : getSkillRepository()
activate reposRepos

reposRepos --> Controller : skillRepository
deactivate reposRepos

Controller -> reposRepos : getCollaboratorRepository()
activate reposRepos

reposRepos --> Controller : collaboratorRepository
deactivate reposRepos

Controller -> EmpRepo : getCollaboratorList()
activate EmpRepo

EmpRepo --> Controller : collaboratorList
deactivate EmpRepo

Controller -> EmpMapper : toDTO(collaboratorList)
activate EmpMapper

EmpMapper -> CollaboratorListDto** : create()

loop for each object in collaboratorList
    EmpMapper -> listEmp : obj = get()
    activate listEmp
    deactivate listEmp
    EmpMapper -> EmpMapper: objDto = toDto(obj)
    activate EmpMapper

    EmpMapper -> CollaboratorDto** : create(obj.getName())
    deactivate EmpMapper
    EmpMapper -> CollaboratorListDto : add(objDto)
    activate CollaboratorListDto
    deactivate CollaboratorListDto
end

deactivate listEmp

EmpMapper -> Controller : CollaboratorListDto
deactivate EmpMapper

Controller --> UI : CollaboratorListDto
deactivate Controller

UI --> HRManager : Displays Collaborator Names list
deactivate UI

HRManager -> UI : Selects Collaborator
activate UI

UI -> Controller : getAvailableSkillListDto(objDto) /' collaboratorName '/ 
activate Controller

Controller -> EmpRepo : getName(objDto) /' collaboratorName '/ 
activate EmpRepo

EmpRepo -> EmpMapper : toModelAndGetName(objDto) /' collaboratorName '/ 
activate EmpMapper

EmpMapper -> CollaboratorDto : collaboratorName = getCollaboratorName()
activate CollaboratorDto
deactivate CollaboratorDto

EmpMapper -> EmpRepo :  collaboratorName  
deactivate EmpMapper

EmpRepo -> Controller :  collaboratorName  
deactivate EmpRepo

Controller -> SkillRepo : getAllSkillNames()
activate SkillRepo

SkillRepo -> Controller : allSkills
deactivate SkillRepo

Controller -> EmpRepo : getAvailableSkillList(collaboratorName, allSkills)
activate EmpRepo

EmpRepo -> EmpRepo : findCollaboratorByName(collaboratorName)
activate EmpRepo
deactivate EmpRepo

EmpRepo -> Collaborator : getAssignedSkills()
activate Collaborator

Collaborator -> EmpRepo  : assignedSkills
deactivate Collaborator
EmpRepo -> EmpRepo : filterAssignedSkills(assignedSkills, allSkills)

EmpRepo --> Controller : availableSkillList
deactivate EmpRepo



Controller -> SkillMapper : toDTO(availableSkillList)
activate SkillMapper

SkillMapper -> SkillListDto** : create()

loop for each object in availableSKillList
    SkillMapper -> listSkill : obj = get()
    activate listSkill
    deactivate listSkill
    SkillMapper -> SkillMapper: objDto = toDto(obj)
    activate SkillMapper

    SkillMapper -> SkillDto** : create(obj.getName())
    deactivate SkillMapper
    SkillMapper -> SkillListDto : add(objDto)
    activate SkillListDto
    deactivate SkillListDto
end

deactivate listEmp

SkillMapper -> Controller : skillListDto
deactivate SkillMapper

Controller --> UI : availableSkillListDto
deactivate Controller

UI --> HRManager : Displays Available Skills to Assign
deactivate UI

HRManager -> UI : Selects Skill and Submits
activate UI

UI -> Controller : assignSkill(objDto) /' collaboratorName, skillName '/
activate Controller

Controller -> EmpRepo : assignSkillToCollaborator(objDto)
activate EmpRepo

EmpRepo -> EmpMapper : toModel(objDto)
activate EmpMapper

EmpMapper -> CollaboratorDto : collaboratorName = getCollaboratorName()
activate CollaboratorDto
deactivate CollaboratorDto

EmpMapper -> SkillDto : skillName = getSkillName()
activate SkillDto

EmpMapper -> EmpRepo : findCollaboratorByName(collaboratorName)
deactivate SkillDto
activate EmpRepo

EmpRepo -> EmpMapper  : collaborator
deactivate EmpRepo

EmpMapper -> SkillRepo : findSkillByName(skillName)

activate SkillRepo

SkillRepo -> EmpMapper  : skill
deactivate SkillRepo

EmpMapper -> Collaborator : assignSkill(skillName)
activate Collaborator


Collaborator --> EmpMapper : true
deactivate Collaborator

EmpMapper --> EmpRepo : true
deactivate EmpMapper

EmpRepo --> Controller : true
deactivate EmpRepo

Controller --> UI : true
deactivate Controller

UI --> HRManager : Displays Operation Success Message
deactivate UI

@enduml
