@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "GSM" as GSM
participant ":AgendaUI" as UI
participant ":ViewDetailsEntryAgendaUI" as UI2
participant ":AgendaController" as CTRL
participant ":ViewDetailsEntryController" as CTRL2
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "entryRepository\n:EntryRepository" as EntryRepository
participant "vehicleRepository\n:VehicleRepository" as VehicleRepository
participant ":Vehicle" as OBJSelected
participant ":VehicleDto" as SelectedDTO
participant "agendaDto : List<VehicleDto>" as ListSelectedDTO
participant "agenda : List<Vehicle>" as ListSelected
participant ":VehicleMapper" as SelectedMAPPER
participant ":Entry" as OBJ
participant ":EntryDto" as DTO
participant ":EntryMapper" as MAPPER
participant "agendaDto : List<EntryDto>" as ListDTO
participant "agenda : List<Entry>" as List


activate GSM

        GSM -> UI : asks to assign a vehicle to an Entry in Agenda

        activate UI

'            UI --> GSM : requests data (reference, description,  informal \n description, technical description, duration, cost)
            'create CTRL
            UI -> CTRL** : create()

            UI -> CTRL : getAgendaList()
            activate CTRL
                        ref over CTRL
                                Get Agenda Entry's List
                        end


            CTRL -> UI : agendaDto
            deactivate CTRL

            UI -> GSM : show Agenda and wait to select one Entry
            deactivate UI

            GSM --> UI : select one Entry
            activate UI

            UI --> UI2** : create()
            activate UI2
            deactivate UI

            UI2 --> CTRL2** : create(entryDto)

            UI2 --> CTRL2 : getVehicleListPossibleForEntry()
            activate CTRL2


             CTRL2 -> RepositorySingleton : getInstance()
                                                    activate RepositorySingleton

                                                        RepositorySingleton --> CTRL2: repositories
                                                    deactivate RepositorySingleton

                                                    CTRL2 -> PLAT : getVehicleRepository()
                                                    activate PLAT

                                                    PLAT -> CTRL2 : vehicleRepository
                                                    deactivate PLAT


                                                    CTRL2 -> PLAT : getEntryRepository()
                                                    activate PLAT

                                                    PLAT -> CTRL2 : entryRepository
                                                    deactivate PLAT

                                                    CTRL2 -> VehicleRepository : getVehicleList()
                                                    activate VehicleRepository

                                                    VehicleRepository -> ListSelected** : create()

                                                    note over ListSelected : loop to populate is omitted



                                                    VehicleRepository -> CTRL2 : vehicleList
                                                    deactivate VehicleRepository

                                                    CTRL2 -> EntryRepository : getAgendaList()
                                                    activate EntryRepository

                                                    EntryRepository -> AgendaList : filterVehiclesNotUseInTime(entryDto,vehicleList)
                                                    activate AgendaList
                                                    ref over AgendaList : method omitted
                                                    deactivate AgendaList

                                                    EntryRepository -> OBJ : getVehicleList()
                                                    activate OBJ
                                                    deactivate OBJ

                                                    EntryRepository -> CTRL2 : vehicleList
                                                    deactivate EntryRepository


                                                    CTRL2 -> SelectedMAPPER : toDTO(vehicleListFilter)
                                                    activate SelectedMAPPER

                                                                                                           SelectedMAPPER -> ListSelectedDTO** : create()


                                                  loop For every Vehicle
                                                                                                              SelectedMAPPER -> SelectedMAPPER : vehicleDTO = vehicleToVehicleDto(vehicle)
                                                                                                              activate SelectedMAPPER

                                                                                                             SelectedMAPPER -> ListSelected : vehicle = get(i)
                                                                                                                                                                      activate ListSelected
                                                                                                                                                                      deactivate ListSelected

                                                                                                              SelectedMAPPER -> SelectedDTO : create(...)
                                                                                                              activate SelectedDTO

                                                                                                              deactivate SelectedDTO
                                                                                                              deactivate SelectedMAPPER

                                                                                                              SelectedMAPPER -> ListSelectedDTO : add(vehicleDto)
                                                                                                              activate ListSelectedDTO
                                                                                                              deactivate ListSelectedDTO
                                                   end
                                                                                                              SelectedMAPPER -> CTRL2 : vehicleDtoList
                                                                                                              deactivate SelectedMAPPER

                                                     CTRL2 -> UI2 : vehicleDtoList
                                                    deactivate CTRL2

             UI2 -> GSM : show entry data and wait for selection vehicle to assign
             deactivate UI2


             GSM -> UI2 : select one vehicle and click on button to assign
             activate UI2
 loop For Every vehicle that he want to add to the entry and are disposable to
            UI2 -> CTRL2 : assignVehicleToEntry(vehicleDto,entryDto)
            activate CTRL2



            CTRL2 -> EntryRepository : assignVehicleToEntry(vehicleDto,entryDto)
            activate EntryRepository

            EntryRepository -> MAPPER : entryDtoToEntry(entryDto)
            activate MAPPER

             MAPPER -> SelectedMAPPER : vehicleDtoToVehicle(vehicleDto)
                        activate SelectedMAPPER


                        SelectedMAPPER -> MAPPER : vehicle
                        deactivate SelectedMAPPER


            MAPPER -> OBJ : setNewVehicle(vehicle)
                        activate OBJ

                        OBJ -> MAPPER : true/false
                        deactivate OBJ

            MAPPER -> EntryRepository : entry
            deactivate MAPPER



            EntryRepository -> CTRL2 : true/false
            deactivate EntryRepository

            CTRL2 -> UI2 : true/false
            deactivate CTRL2
end
            UI2 -> GSM : show operation success
            deactivate UI2




deactivate GSM

@enduml